

/*
 * =============================================================================
 * "Compile-time" params
 * =============================================================================
 */

AC_ngrid = {128,128,128}
AC_len = {6.283185307179586,6.283185307179586,6.283185307179586}

/*
 * =============================================================================
 * Run-time params
 * =============================================================================
 */

// Maximum number of computational steps
AC_max_steps  = 50001
// The interval of steps when standard diagnostic are produced
AC_save_steps = 10
// The interval of steps when slices are written out
AC_slice_steps = 10
// Interval of steps to save snapshot binaries
AC_bin_steps  = 10000 
// Interval on physical time to save snapshot binaries
AC_bin_save_t = 0.5

// Set AC_num_snapshots < 0 if you want to decide snapshot number by time
// interval
AC_num_snapshots = -1 

// Interval of steps between forcing parameter generation
AC_forcing_period_steps = 1

// Interval in time between the same
AC_forcing_period_t = 0.0


// Set to 0 if you want to run the simulation from the beginning, or just a new
// simulation. If continuing from a saved step, specify the step number here.
AC_start_step = 0

// Maximum time in code units. If negative, there is no time limit
AC_max_time = 30.0

// Hydro
AC_cdt = 0.4
AC_cdtv = 0.3
AC_cdts = 1.0
//Kinematic viscosity
AC_nu_visc  = 1e-3
//Speed of sound
AC_cs_sound = 1.0
AC_zeta = 0.00

// Magnetic
AC_eta = 1e-3
AC_mu0 = 1.0

// Forcing
// 0 no helicity, 1 max helicity
AC_relhel = 0.0
AC_forcing_magnitude = 0.08
// Range of wavenumbers
AC_kmin              = 4.5
AC_kmax              = 5.5
// Set so that forcing is active when t > 0 
AC_switch_forcing    = 0.0

// Physical properties of the domain
AC_unit_velocity = 1.0
AC_unit_density = 1.0
AC_unit_length = 1.0

/*
 * =============================================================================
 * Initial conditions
 * =============================================================================
 */
AC_ampl_lnrho = 0.0
AC_ampl_uu = 0.0
