// Generated by Pencil Code build, yet meant to be edited by the user.
// All needed functions are provided, but unneeded ones are not removed.


dUU_dt(){return real3(0.0,0.0,0.0) }

dRHO_dt(){return 0.0 }

dAA_dt(){ return real3(0.0,0.0,0.0) }

dSS_dt(){ return 0.0 }

