#include "$AC_HOME/acc-runtime/stdlib/geometric_multigrid_core.h"
#include "$AC_HOME/acc-runtime/stdlib/poisson.h"
hostdefine AC_GMG_ENABLED (1)

run_const int AC_gmg_number_of_levels = 5
//The stencil values are supposed to be loaded at runtime
//They are generated by the Galerkin definition for the coarse operator
//A_coarse = Restriction(A(Prolongation(U_coarse)))
//
Stencil 
gmg_laplace_level_1
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_level_2
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_level_3
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_level_4
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_1
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_2
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_3
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_4
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

run_const bool AC_use_coarse_galerkin_operators = true
gmg_laplace(Field f, int level)
{
	if(!AC_use_coarse_galerkin_operators) 
	{
		inv_spacing_2 = AC_inv_ds_2/pow(4,int(level))
		return laplace(f,inv_spacing_2)
	}
	if(level == 0) return laplace(f)
	if(level == 1) return gmg_laplace_level_1(f)
	if(level == 2) return gmg_laplace_level_2(f)
	if(level == 3) return gmg_laplace_level_3(f)
	if(level == 4) return gmg_laplace_level_4(f)
	return 0.0;
}

gmg_laplace_neighbours(Field f, int level)
{
	if(!AC_use_coarse_galerkin_operators) 
	{
		inv_spacing_2 = AC_inv_ds_2/pow(4,int(level))
		return laplace_neighbours(f,inv_spacing_2)
	}
	if(level == 0) return laplace_neighbours(f)
	if(level == 1) return gmg_laplace_neighbours_level_1(f)
	if(level == 2) return gmg_laplace_neighbours_level_2(f)
	if(level == 3) return gmg_laplace_neighbours_level_3(f)
	if(level == 4) return gmg_laplace_neighbours_level_4(f)
	return 0.0;
}


Kernel gmg_copy_rhs_to_residual_kernel(GMG_LEVEL level)
{
	write(GMG_RESIDUALS[level],GMG_RHS[level])
}


Kernel gmg_restrict_solution_kernel(GMG_LEVEL level)
{
	int l = level
	restrict_full_weighting(GMG_SOLUTIONS[level],GMG_SOLUTIONS[level+1],get_gmg_level_dims(level))
}


ComputeSteps
gmg_restrict_solution(gmg_boundconds)
{
	gmg_restrict_solution_kernel(AC_GMG_LEVEL)
}


Kernel gmg_residual_kernel(GMG_LEVEL level)
{
	residual = GMG_RHS[level] + gmg_laplace(GMG_SOLUTIONS[level],level)
	write(GMG_RESIDUALS[level],residual)
}

ComputeSteps
gmg_get_residual(gmg_boundconds)
{
	gmg_residual_kernel(AC_GMG_LEVEL)
}
ComputeSteps
gmg_copy_rhs_to_residual(gmg_boundconds)
{
	gmg_copy_rhs_to_residual_kernel(AC_GMG_LEVEL)
}

gmg_laplace_central_coeff(int level)
{
	if(level == 0) return laplace_central_coeff()
	return AC_GMG_CENTRAL_COEFFS[level]
}

gmg_poisson_jacobi_update(int level)
{
	Ax = -gmg_laplace_neighbours(GMG_SOLUTIONS[level],level)
	coef = -gmg_laplace_central_coeff(level)
	return (GMG_RHS[level]-Ax)/coef
}

gmg_poisson_sor_red_black(int color, int level, real omega)
{
	res = (1-omega)*GMG_SOLUTIONS[level] + omega*gmg_poisson_jacobi_update(level)
	if((globalVertexIdx.x + globalVertexIdx.y + globalVertexIdx.z) %2 == color)
	{
		write(GMG_SOLUTIONS[level],res)
	}
	else
	{
		write(GMG_SOLUTIONS[level],GMG_SOLUTIONS[level])
	}
}

Kernel gmg_prolong_solution_kernel(GMG_LEVEL level)
{
	e = trilinear_prolongation(GMG_SOLUTIONS[level+1])
	write(GMG_SOLUTIONS[level],e)
}

ComputeSteps
gmg_prolong_solution(gmg_boundconds)
{
	gmg_prolong_solution_kernel(AC_GMG_LEVEL)
}

Kernel gmg_sor_red(GMG_LEVEL level, real omega)
{
	gmg_poisson_sor_red_black(SOR_RED,level,omega)
}

Kernel gmg_sor_black(GMG_LEVEL level, real omega)
{
	gmg_poisson_sor_red_black(SOR_BLACK,level,omega)
}

ComputeSteps
gmg_poisson_sor_red_black_step(gmg_boundconds)
{
	gmg_sor_red(AC_GMG_LEVEL, AC_SOR_omega)
	gmg_sor_black(AC_GMG_LEVEL, AC_SOR_omega)
}

//Optimized smoother across all of the 7-point stencils
//When going to sixth-order can numerically find optimized
//19-point smoother or even 343-point smoother by minimizing the smoothing factor.
//Credit and further details
//https://arxiv.org/pdf/2206.05543
/**
run_const real AC_omega_for_optimized_smoother = 0.274
run_const real AC_gmg_optimized_smoother_r0 = 8.0/10.0
run_const real AC_gmg_optimized_smoother_r1 = 1.0/10.0

//Example of smoother parameters that were derived numerically
//run_const real AC_omega_for_optimized_smoother = 0.7244
//run_const real AC_gmg_optimized_smoother_r0 = 0.2997
//run_const real AC_gmg_optimized_smoother_r1 = 0.0371

Stencil
optimized_smoother_stencil
{
	[-1][0][0] = AC_gmg_optimized_smoother_r1,
	[1 ][0][0] = AC_gmg_optimized_smoother_r1,
	[0][-1][0] = AC_gmg_optimized_smoother_r1,
	[0][1 ][0] = AC_gmg_optimized_smoother_r1,
	[0][0][-1] = AC_gmg_optimized_smoother_r1,
	[0][0][1 ] = AC_gmg_optimized_smoother_r1,
	[0][0][0]  = AC_gmg_optimized_smoother_r0
}
*/

//This is the full 3x3x3 smoother with numerically derived coeffs that achieve smoothing factor of approx 0.285 which is better than the theoretical best when including only cardinals
run_const real AC_omega_for_optimized_smoother = 1.3699
run_const real AC_gmg_optimized_smoother_coeff_facet_0_r1 = 0.1432
run_const real AC_gmg_optimized_smoother_coeff_facet_1_r1 = 0.0284
run_const real AC_gmg_optimized_smoother_coeff_facet_2_r1 = 0.0081
run_const real AC_gmg_optimized_smoother_coeff_facet_3_r1 = 0.0025
Stencil
optimized_smoother_stencil
{
          [-1][-1][-1] = AC_gmg_optimized_smoother_coeff_facet_3_r1,
          [-1][-1][0] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [-1][-1][1] = AC_gmg_optimized_smoother_coeff_facet_3_r1,
          [-1][0][-1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [-1][0][0] = AC_gmg_optimized_smoother_coeff_facet_1_r1,
          [-1][0][1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [-1][1][-1] = AC_gmg_optimized_smoother_coeff_facet_3_r1,
          [-1][1][0] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [-1][1][1] = AC_gmg_optimized_smoother_coeff_facet_3_r1,
          [0][-1][-1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [0][-1][0] = AC_gmg_optimized_smoother_coeff_facet_1_r1,
          [0][-1][1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [0][0][-1] = AC_gmg_optimized_smoother_coeff_facet_1_r1,
          [0][0][0] = AC_gmg_optimized_smoother_coeff_facet_0_r1,
          [0][0][1] = AC_gmg_optimized_smoother_coeff_facet_1_r1,
          [0][1][-1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [0][1][0] = AC_gmg_optimized_smoother_coeff_facet_1_r1,
          [0][1][1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [1][-1][-1] = AC_gmg_optimized_smoother_coeff_facet_3_r1,
          [1][-1][0] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [1][-1][1] = AC_gmg_optimized_smoother_coeff_facet_3_r1,
          [1][0][-1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [1][0][0] = AC_gmg_optimized_smoother_coeff_facet_1_r1,
          [1][0][1] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [1][1][-1] = AC_gmg_optimized_smoother_coeff_facet_3_r1,
          [1][1][0] = AC_gmg_optimized_smoother_coeff_facet_2_r1,
          [1][1][1] = AC_gmg_optimized_smoother_coeff_facet_3_r1
}

optimized_smoother(Field r, int level)
{
	h2 = AC_ds_2.x*pow(4,int(level))
	return optimized_smoother_stencil(r)*h2
}



Kernel gmg_optimized_smoother_kernel(GMG_LEVEL level)
{
	Field u = GMG_SOLUTIONS[level]
	Field r = GMG_RESIDUALS[level]
	write(u, u + AC_omega_for_optimized_smoother*optimized_smoother(r,level))
}

ComputeSteps gmg_optimized_smoother(gmg_boundconds)
{
	gmg_residual_kernel(AC_GMG_LEVEL)
	gmg_optimized_smoother_kernel(AC_GMG_LEVEL)
}



Kernel gmg_write_del2_kernel()
{
	write(GMG_RESIDUALS[0],laplace(GMG_SOLUTIONS[0]))
}


ComputeSteps
gmg_write_del2(gmg_boundconds)
{
	gmg_write_del2_kernel()
}

global output real AC_GMG_residual2
Kernel gmg_get_residual_norm_kernel(GMG_LEVEL level)
{
	const real res = -laplace(GMG_SOLUTIONS[level])
	r = GMG_RHS[level]- res
	reduce_sum(r*r,AC_GMG_residual2)
}

ComputeSteps
gmg_get_residual_norm(gmg_boundconds)
{
	gmg_get_residual_norm_kernel(AC_GMG_LEVEL)
}
