#include "$AC_HOME/acc-runtime/stdlib/grid_transfer_functions.h"
hostdefine AC_GMG_ENABLED (1)

int3 AC_mlocal_gmg_level_0 = AC_mlocal
int3 AC_mlocal_gmg_level_1 = ((AC_mlocal_gmg_level_0-1)/2)+1
int3 AC_mlocal_gmg_level_2 = ((AC_mlocal_gmg_level_1-1)/2)+1
int3 AC_mlocal_gmg_level_3 = ((AC_mlocal_gmg_level_2-1)/2)+1
int3 AC_mlocal_gmg_level_4 = ((AC_mlocal_gmg_level_3-1)/2)+1

int3 AC_nlocal_gmg_level_0 = AC_mlocal_gmg_level_0 - 2*NGHOST
int3 AC_nlocal_gmg_level_1 = AC_mlocal_gmg_level_1 - 2*NGHOST
int3 AC_nlocal_gmg_level_2 = AC_mlocal_gmg_level_2 - 2*NGHOST
int3 AC_nlocal_gmg_level_3 = AC_mlocal_gmg_level_3 - 2*NGHOST
int3 AC_nlocal_gmg_level_4 = AC_mlocal_gmg_level_4 - 2*NGHOST

dims(AC_mlocal_gmg_level_0) Field GMG_SOLUTION_0
dims(AC_mlocal_gmg_level_1) Field GMG_SOLUTION_1 
dims(AC_mlocal_gmg_level_2) Field GMG_SOLUTION_2
dims(AC_mlocal_gmg_level_3) Field GMG_SOLUTION_3
dims(AC_mlocal_gmg_level_4) Field GMG_SOLUTION_4

auxiliary dims(AC_mlocal_gmg_level_0) Field GMG_INITIAL_RHS
auxiliary dims(AC_mlocal_gmg_level_1) Field GMG_RHS_1
auxiliary dims(AC_mlocal_gmg_level_2) Field GMG_RHS_2
auxiliary dims(AC_mlocal_gmg_level_3) Field GMG_RHS_3
auxiliary dims(AC_mlocal_gmg_level_4) Field GMG_RHS_4

//Need to be communicated if use other smoothers than gauss-seidel or jacobi
communicated auxiliary dims(AC_mlocal_gmg_level_0) Field GMG_RESIDUAL_0
communicated auxiliary dims(AC_mlocal_gmg_level_1) Field GMG_RESIDUAL_1 
communicated auxiliary dims(AC_mlocal_gmg_level_2) Field GMG_RESIDUAL_2
communicated auxiliary dims(AC_mlocal_gmg_level_3) Field GMG_RESIDUAL_3
communicated auxiliary dims(AC_mlocal_gmg_level_4) Field GMG_RESIDUAL_4

dconst real AC_GMG_CENTRAL_COEFFS[5]

const Field GMG_SOLUTIONS =
	[
		GMG_SOLUTION_0,
		GMG_SOLUTION_1,
		GMG_SOLUTION_2,
		GMG_SOLUTION_3,
		GMG_SOLUTION_4
	]

const Field GMG_RHS =
	[
		GMG_INITIAL_RHS,
		GMG_RHS_1,
		GMG_RHS_2,
		GMG_RHS_3,
		GMG_RHS_4
	]

const Field GMG_RESIDUALS =
	[
		GMG_RESIDUAL_0,
		GMG_RESIDUAL_1,
		GMG_RESIDUAL_2,
		GMG_RESIDUAL_3,
		GMG_RESIDUAL_4
	]

enum GMG_LEVEL
{
	GMG_LEVEL_0,
	GMG_LEVEL_1,
	GMG_LEVEL_2,
	GMG_LEVEL_3,
	GMG_LEVEL_4
}

input GMG_LEVEL AC_GMG_LEVEL

//The stencil values are supposed to be loaded at runtime
//They are generated by the Galerkin definition for the coarse operator
//A_coarse = Restriction(A(Prolongation(U_coarse)))
//
Stencil 
gmg_laplace_level_1
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_level_2
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_level_3
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_level_4
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_1
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_2
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_3
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[0][0][0]    = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

Stencil 
gmg_laplace_neighbours_level_4
{
	[-1][-1][-1] = -1.0, 
	[0][-1][-1]  = -1.0, 
	[1][-1][-1]  = -1.0, 
	[-1][0][-1]  = -1.0, 
	[0][0][-1]   = -1.0, 
	[1][0][-1]   = -1.0, 
	[-1][1][-1]  = -1.0, 
	[0][1][-1]   = -1.0, 
	[1][1][-1]   = -1.0, 
	[-1][-1][0]  = -1.0, 
	[0][-1][0]   = -1.0, 
	[1][-1][0]   = -1.0, 
	[-1][0][0]   = -1.0, 
	[1][0][0]    = -1.0, 
	[-1][1][0]   = -1.0, 
	[0][1][0]    = -1.0, 
	[1][1][0]    = -1.0, 
	[-1][-1][1]  = -1.0, 
	[0][-1][1]   = -1.0, 
	[1][-1][1]   = -1.0, 
	[-1][0][1]   = -1.0, 
	[0][0][1]    = -1.0, 
	[1][0][1]    = -1.0, 
	[-1][1][1]   = -1.0, 
	[0][1][1]    = -1.0, 
	[1][1][1]    = -1.0 
}

gmg_laplace(Field f, int level)
{
	if(level == 0) return laplace(f)
	if(level == 1) return gmg_laplace_level_1(f)
	if(level == 2) return gmg_laplace_level_2(f)
	if(level == 3) return gmg_laplace_level_3(f)
	if(level == 4) return gmg_laplace_level_4(f)
	return 0.0;
}

gmg_laplace_neighbours(Field f, int level)
{
	if(level == 0) return laplace_neighbours(f)
	if(level == 1) return gmg_laplace_neighbours_level_1(f)
	if(level == 2) return gmg_laplace_neighbours_level_2(f)
	if(level == 3) return gmg_laplace_neighbours_level_3(f)
	if(level == 4) return gmg_laplace_neighbours_level_4(f)
	return 0.0;
}

Kernel gmg_restrict_residual_kernel(GMG_LEVEL level)
{
	restrict_full_weighting(GMG_RESIDUALS[level],GMG_RHS[level+1])
	//The residual is most likely small so zero is a meaningful starting value
	write(GMG_SOLUTIONS[level+1],0.0)
}

Kernel gmg_copy_rhs_to_residual_kernel(GMG_LEVEL level)
{
	write(GMG_RESIDUALS[level],GMG_RHS[level])
}

Kernel gmg_get_correction_from_next_level_kernel(GMG_LEVEL level)
{
	e = trilinear_prolongation(GMG_SOLUTIONS[level+1])
	write(GMG_SOLUTIONS[level],GMG_SOLUTIONS[level]+e)
}

Kernel gmg_restrict_solution_kernel(GMG_LEVEL level)
{
	restrict_full_weighting(GMG_SOLUTIONS[level],GMG_SOLUTIONS[level+1])
}

ComputeSteps
gmg_restrict_residual(gmg_boundconds)
{
	gmg_restrict_residual_kernel(AC_GMG_LEVEL)
}

ComputeSteps
gmg_restrict_solution(gmg_boundconds)
{
	gmg_restrict_solution_kernel(AC_GMG_LEVEL)
}

ComputeSteps
gmg_get_correction_from_next_level(gmg_boundconds)
{
	gmg_get_correction_from_next_level_kernel(AC_GMG_LEVEL)
}

Kernel gmg_residual_kernel(GMG_LEVEL level)
{
	residual = GMG_RHS[level] + gmg_laplace(GMG_SOLUTIONS[level],level)
	write(GMG_RESIDUALS[level],residual)
}

ComputeSteps
gmg_get_residual(gmg_boundconds)
{
	gmg_residual_kernel(AC_GMG_LEVEL)
}
ComputeSteps
gmg_copy_rhs_to_residual(gmg_boundconds)
{
	gmg_copy_rhs_to_residual_kernel(AC_GMG_LEVEL)
}

gmg_laplace_central_coeff(int level)
{
	if(level == 0) return laplace_central_coeff()
	return AC_GMG_CENTRAL_COEFFS[level]
}

gmg_poisson_jacobi_update(int level)
{
	Ax = -gmg_laplace_neighbours(GMG_SOLUTIONS[level],level)
	coef = -gmg_laplace_central_coeff(level)
	return (GMG_RHS[level]-Ax)/coef
}

gmg_poisson_sor_red_black(int color, int level, real omega)
{
	res = (1-omega)*GMG_SOLUTIONS[level] + omega*gmg_poisson_jacobi_update(level)
	if((globalVertexIdx.x + globalVertexIdx.y + globalVertexIdx.z) %2 == color)
	{
		write(GMG_SOLUTIONS[level],res)
	}
	else
	{
		write(GMG_SOLUTIONS[level],GMG_SOLUTIONS[level])
	}
}

Kernel gmg_prolong_solution_kernel(GMG_LEVEL level)
{
	e = trilinear_prolongation(GMG_SOLUTIONS[level+1])
	write(GMG_SOLUTIONS[level],e)
}

ComputeSteps
gmg_prolong_solution(gmg_boundconds)
{
	gmg_prolong_solution_kernel(AC_GMG_LEVEL)
}

Kernel gmg_sor_red(GMG_LEVEL level)
{
	gmg_poisson_sor_red_black(SOR_RED,level,AC_SOR_omega)
}

Kernel gmg_sor_black(GMG_LEVEL level)
{
	gmg_poisson_sor_red_black(SOR_BLACK,level,AC_SOR_omega)
}

ComputeSteps
gmg_poisson_sor_red_black_step(gmg_boundconds)
{
	gmg_sor_red(AC_GMG_LEVEL)
	gmg_sor_black(AC_GMG_LEVEL)
}

//Optimized smoother across all of the 7-point stencils
//When going to sixth-order can numerically find optimized
//19-point smoother or even 343-point smoother by minimizing the smoothing factor.
//Credit and further details
//https://arxiv.org/pdf/2206.05543
Stencil
optimized_smoother_stencil
{
	[-1][0][0] = 1.0/10.0,
	[1 ][0][0] = 1.0/10.0,
	[0][-1][0] = 1.0/10.0,
	[0][1 ][0] = 1.0/10.0,
	[0][0][-1] = 1.0/10.0,
	[0][0][1 ] = 1.0/10.0,

	[0][0][0] = 8.0/10.0
}

optimized_smoother(Field r, int level)
{
	h2 = AC_ds_2.x*pow(4,int(level))
	return optimized_smoother_stencil(r)*h2
}


Kernel gmg_optimized_smoother_kernel(GMG_LEVEL level)
{
	Field u = GMG_SOLUTIONS[level]
	Field r = GMG_RESIDUALS[level]
	const real omega = 0.274
	write(u, u + omega*optimized_smoother(r,level))
}

ComputeSteps gmg_optimized_smoother(gmg_boundconds)
{
	gmg_residual_kernel(AC_GMG_LEVEL)
	gmg_optimized_smoother_kernel(AC_GMG_LEVEL)
}



Kernel gmg_write_del2_kernel()
{
	write(GMG_RESIDUALS[0],laplace(GMG_SOLUTIONS[0]))
}


ComputeSteps
gmg_write_del2(gmg_boundconds)
{
	gmg_write_del2_kernel()
}

output real AC_GMG_residual2
Kernel gmg_get_residual_norm_kernel()
{
	const real res = -laplace(GMG_SOLUTIONS[0])
	r = GMG_INITIAL_RHS - res
	reduce_sum(r*r,AC_GMG_residual2)
}

ComputeSteps
gmg_get_residual_norm(gmg_boundconds)
{
	gmg_get_residual_norm_kernel()
}
