/*
    Copyright (C) 2026 Ondřej Míchal.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <any>

#include <mpi.h>
#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/vector.h>
#include <nanobind/ndarray.h>
#include <mpi4py/mpi4py.h>

#include "astaroth.h"
#include "astaroth_utils.h"

namespace nb = nanobind;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

MPI_Comm py_comm_to_cxx_comm(nb::object py_comm) {
    MPI_Comm *cxx_comm = PyMPIComm_Get(py_comm.ptr());

    if (cxx_comm == NULL)
        throw nb::python_error();

    return *cxx_comm;
}

// class AcTaskGraphBoxed {
// public:
//     AcTaskGraphBoxed(AcDSLTaskGraph graph) {
//         this->ptr   = acGetOptimizedDSLTaskGraph(graph);
//     }
//     ~AcTaskGraphBoxed() {}
//
// private:
//     AcTaskGraph *ptr;
// };

NB_MODULE(astaroth, m)
{
    nb::set_leak_warnings(false);

    // Initialize the mpi4py C API
    if (import_mpi4py() < 0) {
        throw nb::python_error();
    }

    m.doc() = "Astaroth is a multi-GPU library designed for high-order stencil computations with a "
              "special focus on the requirements of multiphysics applications on modern HPC "
              "systems. It provides a multi-GPU and single-GPU APIs, a domain-specific language "
              "for expressing stencil codes in a high-level syntax, and an optimizing compiler "
              "that translates DSL sources into CUDA/HIP subroutines that exhibit near handtuned "
              "performance.";

    /* START: Manually written bindings. */
    // auto pyClassAcTaskGraph = nb::class_<AcTaskGraphBoxed>(m, "TaskGraph");

    m.def(
        "communicator_set_communicator",
        [](AcCommunicator *communicator, nb::object py_comm) {
            acCommunicatorSetCommunicator(communicator, py_comm_to_cxx_comm(py_comm));
        }
    );
    /* END: Manually written bindings. */

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
