/*
    Copyright (C) 2026 Ondřej Míchal.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/vector.h>
#include <nanobind/ndarray.h>

#include "astaroth.h"
#include "astaroth_device.h"

namespace nb = nanobind;

template<typename T>
struct Opaque {
    T ptr;
};

NB_MAKE_OPAQUE(Opaque<Device>);

// namespace nanobind::detail {
//
// template <> struct type_caster<OpaquePtrWrap<Device>> {
//     NB_TYPE_CASTER(OpaquePtrWrap<Device>, const_name("Device"));
//
//     bool from_python(handle src, uint8_t flags, cleanup_list *cleanup) {
//         if (!src || !nb::isinstance<nb::object>(src))
//             return false;
//
//         // Require the Python object to be a HandleWrapper instance.
//         // The actual check depends on how HandleWrapper is exposed.
//         if (!nb::isinstance(src, nb::type<OpaquePtrWrap<Device>>()))
//             return false;
//
//         auto wrapper = nb::cast<OpaquePtrWrap<Device>>(src);
//
//         value.ptr = wrapper.ptr;
//
//         return true;
//     }
//
//     static handle from_cpp(const OpaquePtrWrap<Device> &src,
//                            rv_policy policy,
//                            cleanup_list *cleanup) {
//         if (!src.ptr)
//             return nb::none().release();
//
//         return nb::cast(src, policy);
//     }
// };
//
// }

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NB_MODULE(device, m)
{
    m.doc() = "Astaroth is a multi-GPU library designed for high-order stencil computations with a "
              "special focus on the requirements of multiphysics applications on modern HPC "
              "systems. It provides a multi-GPU and single-GPU APIs, a domain-specific language "
              "for expressing stencil codes in a high-level syntax, and an optimizing compiler "
              "that translates DSL sources into CUDA/HIP subroutines that exhibit near handtuned "
              "performance.";

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
