/*
    Copyright (C) 2026 Ondřej Míchal.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <any>

#include <mpi.h>
#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/vector.h>
#include <nanobind/ndarray.h>
#include <mpi4py/mpi4py.h>

#include "astaroth.h"

namespace nb = nanobind;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// NB_MAKE_OPAQUE(struct ompi_communicator_t);
// NB_MAKE_OPAQUE(MPI_Comm);
//
// namespace nanobind::detail {
//
// template <> struct type_caster<struct ompi_communicator> {
// public:
//     NB_TYPE_CASTER(struct ompi_communicator, const_name("MPICommunicator"))
//
//     bool from_python(handle src, uint8_t flags, cleanup_list *cleanup) noexcept {
//         MPI_Comm *comm = PyMPIComm_Get(src.ptr());
//
//         // Check that we have been passed an mpi4py communicator.
//         if (comm == nullptr) {
//           PyErr_Clear();
//           return false;
//         }
//
//         // Convert to regular MPI communicator
//         value = *comm;
//         return true;
//     }
//
//     static handle from_cpp(const MPI_Comm &&src, rv_policy policy, cleanup_list *cleanup) {
//         return PyMPIComm_New(src);
//     }
// };

// template <> struct type_caster<struct ompi_communicator *> {
//     // template <typename MPI_Comm> using Cast = precise_cast_t<MPI_Comm>;
//
//     // static constexpr auto Name = "mpi4py_comm";
//
//     using Type = struct ompi_communicator *;
//     static constexpr auto Name = const_name<Type>();
//     template <typename Type> using Cast = movable_cast_t<std::any(Type)>;
//     explicit operator Type*() { return nullptr; }
//
//     MPI_Comm value;
//
//     bool from_python(handle src, uint8_t flags, cleanup_list *cleanup) noexcept {
//         MPI_Comm *comm = PyMPIComm_Get(src.ptr());
//
//         // Check that we have been passed an mpi4py communicator.
//         if (comm == nullptr) {
//           PyErr_Clear();
//           return false;
//         }
//
//         // Convert to regular MPI communicator
//         value = *comm;
//         return true;
//     }
//
//     static handle from_cpp(MPI_Comm &&src, rv_policy policy, cleanup_list *cleanup) {
//         return PyMPIComm_New(src);
//     }
// };

// template <> struct type_caster<struct ompi_communicator_t *> {
//     //NB_TYPE_CASTER(struct ompi_communicator_t *, const_name("mpi4py_comm"))
//
//     using Type = struct ompi_communicator_t *;
//     static constexpr auto Name = const_name<Type>();
//     template <typename Type> using Cast = movable_cast_t<std::any(Type)>;
//     explicit operator Type*() { return nullptr; }
//
//     MPI_Comm value;
//
//     bool from_python(handle src, uint8_t flags, cleanup_list *cleanup) noexcept {
//         MPI_Comm *comm = PyMPIComm_Get(src.ptr());
//
//         // Check that we have been passed an mpi4py communicator.
//         if (comm == nullptr) {
//           PyErr_Clear();
//           return false;
//         }
//
//         // Convert to regular MPI communicator
//         value = *comm;
//         return true;
//     }
//
//     static handle from_cpp(struct ompi_communicator_t *src, rv_policy policy, cleanup_list *cleanup) {
//         return PyMPIComm_New(src);
//     }
// };
//
// }

MPI_Comm py_comm_to_cxx_comm(nb::object py_comm) {
    MPI_Comm *cxx_comm = PyMPIComm_Get(py_comm.ptr());

    if (cxx_comm == NULL)
        throw nb::python_error();

    return *cxx_comm;
}

NB_MODULE(core, m)
{
    // Initialize the mpi4py C API
    if (import_mpi4py() < 0) {
        throw nb::python_error();
    }

    m.doc() = "Astaroth is a multi-GPU library designed for high-order stencil computations with a "
              "special focus on the requirements of multiphysics applications on modern HPC "
              "systems. It provides a multi-GPU and single-GPU APIs, a domain-specific language "
              "for expressing stencil codes in a high-level syntax, and an optimizing compiler "
              "that translates DSL sources into CUDA/HIP subroutines that exhibit near handtuned "
              "performance.";

    /* START: Manually written bindings. */
    m.def(
        "communicator_set_communicator",
        [](AcCommunicator *communicator, nb::object py_comm) {
            acCommunicatorSetCommunicator(communicator, py_comm_to_cxx_comm(py_comm));
        }
    );
    /* END: Manually written bindings. */

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
