/*
    Copyright (C) 2026 Ondřej Míchal.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <any>

#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/vector.h>
#include <nanobind/ndarray.h>
#include <mpi4py/mpi4py.h>

#include "astaroth.h"
#include "astaroth_grid.h"

namespace nb = nanobind;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


NB_MAKE_OPAQUE(AcTaskGraph);
NB_MAKE_OPAQUE(struct node_s);
NB_MAKE_OPAQUE(Node);
NB_MAKE_OPAQUE(struct device_s);
NB_MAKE_OPAQUE(Device);
// NB_MAKE_OPAQUE(struct ompi_communicator_t);
// NB_MAKE_OPAQUE(MPI_Comm);

namespace nanobind::detail {

template <> struct type_caster<MPI_Comm> {
    // template <typename MPI_Comm> using Cast = precise_cast_t<MPI_Comm>;

    static constexpr auto Name = "mpi4py_comm";

    MPI_Comm value;

    bool from_python(handle src, uint8_t flags, cleanup_list *cleanup) noexcept {
        MPI_Comm *comm = PyMPIComm_Get(src.ptr());

        // Check that we have been passed an mpi4py communicator.
        if (comm == nullptr) {
          PyErr_Clear();
          return false;
        }

        // Convert to regular MPI communicator
        value = *comm;
        return true;
    }

    static handle from_cpp(MPI_Comm &&src, rv_policy policy, cleanup_list *cleanup) {
        return PyMPIComm_New(src);
    }
};

template <> struct type_caster<struct ompi_communicator_t> {
    //NB_TYPE_CASTER(struct ompi_communicator_t *, const_name("mpi4py_comm"))

    using Type = struct ompi_communicator_t;
    static constexpr auto Name = const_name<Type>();
    template <typename Type> using Cast = movable_cast_t<std::any(Type)>;
    explicit operator Type*() { return nullptr; }

    MPI_Comm value;

    bool from_python(handle src, uint8_t flags, cleanup_list *cleanup) noexcept {
        MPI_Comm *comm = PyMPIComm_Get(src.ptr());

        // Check that we have been passed an mpi4py communicator.
        if (comm == nullptr) {
          PyErr_Clear();
          return false;
        }

        // Convert to regular MPI communicator
        value = *comm;
        return true;
    }

    static handle from_cpp(struct ompi_communicator_t *src, rv_policy policy, cleanup_list *cleanup) {
        return PyMPIComm_New(src);
    }
};

}


NB_MODULE(grid, m)
{
    // Initialize the mpi4py C API
    if (import_mpi4py() < 0) {
        throw nb::python_error();
    }

    m.doc() = "Astaroth is a multi-GPU library designed for high-order stencil computations with a "
              "special focus on the requirements of multiphysics applications on modern HPC "
              "systems. It provides a multi-GPU and single-GPU APIs, a domain-specific language "
              "for expressing stencil codes in a high-level syntax, and an optimizing compiler "
              "that translates DSL sources into CUDA/HIP subroutines that exhibit near handtuned "
              "performance.";

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:astaroth_grid.h>    ////////////////////
    // #if AC_MPI_ENABLED
    //

    m.def("mpi_init",
        ac_MPI_Init, "*\nCalls MPI_Init and creates a separate communicator for Astaroth procs with MPI_Comm_split, color =\n666 Any program running in the same MPI process space must also call MPI_Comm_split with some color\n!= 666. OTHERWISE this call will hang.\n\nReturns AC_SUCCESS on successfullly initializing MPI and creating a communicator.\n\nReturns AC_FAILURE otherwise.\n");

    m.def("mpi_init_thread",
        ac_MPI_Init_thread,
        nb::arg("thread_level"),
        "*\nCalls MPI_Init_thread with the provided thread_level and creates a separate communicator for\nAstaroth procs with MPI_Comm_split, color = 666 Any program running in the same MPI process space\nmust also call MPI_Comm_split with some color != 666. OTHERWISE this call will hang.\n\nReturns AC_SUCCESS on successfullly initializing MPI with the requested thread level and creating a\ncommunicator.\n\nReturns AC_FAILURE otherwise.\n");

    m.def("mpi_finalize",
        ac_MPI_Finalize, "*\nDestroys the communicator and calls MPI_Finalize\n");

    m.def("mpi_comm_rank",
        ac_MPI_Comm_rank, "* Returns the rank of the Astaroth communicator");

    m.def("grid_mpi_sub_comms",
        acGridMPISubComms);

    m.def("mpi_comm_size",
        ac_MPI_Comm_size, "* Returns the size of the Astaroth communicator");

    m.def("mpi_barrier",
        ac_MPI_Barrier, "* Calls MPI_Barrier on the Astaroth communicator");

    m.def("grid_init_base",
        acGridInitBase, nb::arg("mesh"));

    m.def("grid_init",
        nb::overload_cast<const AcMeshInfo>(acGridInit), nb::arg("info"));

    m.def("grid_init",
        nb::overload_cast<const AcMesh>(acGridInit), nb::arg("mesh"));

    m.def("grid_quit",
        acGridQuit, "*\nResets all devices on the current grid.\n");

    m.def("grid_randomize",
        acGridRandomize, "* Randomizes the local mesh");

    m.def("grid_synchronize_stream",
        acGridSynchronizeStream, nb::arg("stream"));

    m.def("grid_load_scalar_uniform",
        acGridLoadScalarUniform, nb::arg("stream"), nb::arg("param"), nb::arg("value"));

    m.def("grid_load_vector_uniform",
        acGridLoadVectorUniform, nb::arg("stream"), nb::arg("param"), nb::arg("value"));

    m.def("grid_load_int_uniform",
        acGridLoadIntUniform, nb::arg("stream"), nb::arg("param"), nb::arg("value"));

    m.def("grid_load_int3_uniform",
        acGridLoadInt3Uniform, nb::arg("stream"), nb::arg("param"), nb::arg("value"));

    m.def("grid_load_mesh",
        acGridLoadMesh, nb::arg("stream"), nb::arg("host_mesh"));

    m.def("grid_store_mesh",
        acGridStoreMesh, nb::arg("stream"), nb::arg("host_mesh"));

    m.def("grid_integrate",
        acGridIntegrate, nb::arg("stream"), nb::arg("dt"));

    m.def("grid_swap_buffers",
        acGridSwapBuffers);

    m.def("grid_halo_exchange",
        acGridHaloExchange);

    m.def("grid_periodic_boundconds",
        acGridPeriodicBoundconds, nb::arg("stream"));

    m.def("grid_reduce_scal",
        acGridReduceScal, nb::arg("stream"), nb::arg("reduction"), nb::arg("vtxbuf_handle"), nb::arg("result"));

    m.def("grid_reduce_vec",
        acGridReduceVec, nb::arg("stream"), nb::arg("reduction"), nb::arg("vtxbuf0"), nb::arg("vtxbuf1"), nb::arg("vtxbuf2"), nb::arg("result"));

    m.def("grid_reduce_vec_scal",
        acGridReduceVecScal, nb::arg("stream"), nb::arg("reduction"), nb::arg("vtxbuf0"), nb::arg("vtxbuf1"), nb::arg("vtxbuf2"), nb::arg("vtxbuf3"), nb::arg("result"));

    m.def("grid_reduce_xy",
        acGridReduceXY, nb::arg("stream"), nb::arg("field"), nb::arg("profile"), nb::arg("reduction"));


    auto pyEnumAccessType =
        nb::enum_<AccessType>(m, "AccessType", nb::is_arithmetic(), "")
            .value("access_read", ACCESS_READ, "")
            .value("access_write", ACCESS_WRITE, "");


    m.def("grid_access_mesh_on_disk_synchronous",
        acGridAccessMeshOnDiskSynchronous, nb::arg("field"), nb::arg("dir"), nb::arg("label"), nb::arg("type"));

    m.def("grid_disk_access_launch",
        acGridDiskAccessLaunch, nb::arg("type"));

    m.def("grid_write_slices_to_disk_launch",
        acGridWriteSlicesToDiskLaunch,
        nb::arg("dir"), nb::arg("step_number"), nb::arg("simulation_time"),
        "Asynchronous. Need to call acGridDiskAccessSync afterwards");

    m.def("grid_write_slices_to_disk_synchronous",
        acGridWriteSlicesToDiskSynchronous,
        nb::arg("dir"), nb::arg("step_number"), nb::arg("simulation_time"),
        "Synchronous. No need to call acGridDiskAccessSync afterwards");

    m.def("grid_write_slices_to_disk_collective_synchronous",
        acGridWriteSlicesToDiskCollectiveSynchronous,
        nb::arg("dir"), nb::arg("step_number"), nb::arg("simulation_time"),
        "Synchronous");

    m.def("grid_write_mesh_to_disk_launch",
        acGridWriteMeshToDiskLaunch,
        nb::arg("dir"), nb::arg("label"),
        "Asynchronous. Need to call acGridDiskAccessSync afterwards");

    m.def("grid_disk_access_sync",
        acGridDiskAccessSync);

    m.def("grid_read_varfile_to_mesh",
        acGridReadVarfileToMesh, nb::arg("file"), nb::arg("fields"), nb::arg("num_fields"), nb::arg("nn"), nb::arg("rr"));

    m.def("grid_access_mesh_on_disk_synchronous_distributed",
        acGridAccessMeshOnDiskSynchronousDistributed,
        nb::arg("vtxbuf"), nb::arg("dir"), nb::arg("label"), nb::arg("type"),
        "Quick hack for the hero run, will be removed in future builds");

    m.def("grid_access_mesh_on_disk_synchronous_collective",
        acGridAccessMeshOnDiskSynchronousCollective,
        nb::arg("vtxbuf"), nb::arg("dir"), nb::arg("label"), nb::arg("type"),
        "Quick hack for the hero run, will be removed in future builds");


    auto pyEnumAcTaskType =
        nb::enum_<AcTaskType>(m, "AcTaskType", nb::is_arithmetic(), "")
            .value("tasktype_no_op", TASKTYPE_NO_OP, "")
            .value("tasktype_compute", TASKTYPE_COMPUTE, "")
            .value("tasktype_haloexchange", TASKTYPE_HALOEXCHANGE, "")
            .value("tasktype_boundcond", TASKTYPE_BOUNDCOND, "")
            .value("tasktype_reduce", TASKTYPE_REDUCE, "")
            .value("tasktype_scan", TASKTYPE_SCAN, "")
            .value("tasktype_ray_update", TASKTYPE_RAY_UPDATE, "")
            .value("tasktype_periodic_ray", TASKTYPE_PERIODIC_RAY, "");


    m.def("boundary_to_str",
        ac_boundary_to_str, nb::arg("boundary"));

    m.def("analysis_get_bc_info",
        acAnalysisGetBCInfo, nb::arg("info"), nb::arg("bc"), nb::arg("boundary"));


    auto pyClassfacet_class_range =
        nb::class_<facet_class_range>
            (m, "facet_class_range", "")
        .def("__init__", [](facet_class_range * self, int min = int(), int max = int())
        {
            new (self) facet_class_range();  // placement new
            auto r_ctor_ = self;
            r_ctor_->min = min;
            r_ctor_->max = max;
        },
        nb::arg("min") = int(), nb::arg("max") = int()
        )
        .def_rw("min", &facet_class_range::min, "")
        .def_rw("max", &facet_class_range::max, "")
        ;


    m.def("scan",
        nb::overload_cast<Field *, const size_t, const int3>(acScan), nb::arg("fields"), nb::arg("num_fields"), nb::arg("direction"));

    m.def("scan",
        nb::overload_cast<std::vector<Field>, const int3>(acScan), nb::arg("fields"), nb::arg("ray_direction"));

    m.def("periodic_ray",
        acPeriodicRay, nb::arg("fields"), nb::arg("num_fields"), nb::arg("direction"));

    m.def("get_compute_steps_b_cs",
        acGetComputeStepsBCs, nb::arg("graph"));

    m.def("grid_clear_task_graph_cache",
        acGridClearTaskGraphCache);

    m.def("grid_launch_kernel",
        acGridLaunchKernel, nb::arg("stream"), nb::arg("kernel"), nb::arg("start"), nb::arg("end"));

    m.def("function_always_false",
        ac_function_always_false);
    // #if __cplusplus
    //

    m.def("ray_update",
        nb::overload_cast<const AcKernel, const AcBoundary, const int3, Field *, const size_t, Field *, const size_t, KernelParamsLoader>(acRayUpdate), nb::arg("kernel"), nb::arg("boundary"), nb::arg("ray_direction"), nb::arg("fields_in"), nb::arg("num_fields_in"), nb::arg("fields_out"), nb::arg("num_fields_out"), nb::arg("loader"));

    m.def("get_optimized_dsl_task_graph",
        [](const AcDSLTaskGraph graph, const Volume start, const Volume end) -> void *
        {
            auto acGetOptimizedDSLTaskGraph_adapt_force_lambda = [](const AcDSLTaskGraph graph, const Volume start, const Volume end) -> void *
            {
                auto lambda_result = acGetOptimizedDSLTaskGraph(graph, start, end);
                return lambda_result;
            };

            return acGetOptimizedDSLTaskGraph_adapt_force_lambda(graph, start, end);
        },
        nb::arg("graph"), nb::arg("start"), nb::arg("end"),
        nb::rv_policy::reference);

    m.def("get_optimized_dsl_task_graph",
        [](const AcDSLTaskGraph graph, const Volume start, const Volume end, const bool globally_imposed_bcs) -> void *
        {
            auto acGetOptimizedDSLTaskGraph_adapt_force_lambda = [](const AcDSLTaskGraph graph, const Volume start, const Volume end, const bool globally_imposed_bcs) -> void *
            {
                auto lambda_result = acGetOptimizedDSLTaskGraph(graph, start, end, globally_imposed_bcs);
                return lambda_result;
            };

            return acGetOptimizedDSLTaskGraph_adapt_force_lambda(graph, start, end, globally_imposed_bcs);
        },
        nb::arg("graph"), nb::arg("start"), nb::arg("end"), nb::arg("globally_imposed_bcs"),
        nb::rv_policy::reference);

    m.def("get_optimized_dsl_task_graph",
        [](const AcDSLTaskGraph graph, const bool globally_imposed_bcs) -> void *
        {
            auto acGetOptimizedDSLTaskGraph_adapt_force_lambda = [](const AcDSLTaskGraph graph, const bool globally_imposed_bcs) -> void *
            {
                auto lambda_result = acGetOptimizedDSLTaskGraph(graph, globally_imposed_bcs);
                return lambda_result;
            };

            return acGetOptimizedDSLTaskGraph_adapt_force_lambda(graph, globally_imposed_bcs);
        },
        nb::arg("graph"), nb::arg("globally_imposed_bcs"),
        nb::rv_policy::reference);

    m.def("get_optimized_dsl_task_graph",
        [](const AcDSLTaskGraph graph, const bool globally_imposed_bcs, const AcDSLTaskGraph bc_graph) -> void *
        {
            auto acGetOptimizedDSLTaskGraph_adapt_force_lambda = [](const AcDSLTaskGraph graph, const bool globally_imposed_bcs, const AcDSLTaskGraph bc_graph) -> void *
            {
                auto lambda_result = acGetOptimizedDSLTaskGraph(graph, globally_imposed_bcs, bc_graph);
                return lambda_result;
            };

            return acGetOptimizedDSLTaskGraph_adapt_force_lambda(graph, globally_imposed_bcs, bc_graph);
        },
        nb::arg("graph"), nb::arg("globally_imposed_bcs"), nb::arg("bc_graph"),
        nb::rv_policy::reference);
    // #endif
    //
    // #endif
    ////////////////////    </generated_from:astaroth_grid.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
