/*
    Copyright (C) 2026 Ondřej Míchal.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/vector.h>
#include <nanobind/ndarray.h>

#include "astaroth_utils.h"

namespace nb = nanobind;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


NB_MODULE(utils, m)
{
    m.doc() = "Astaroth is a multi-GPU library designed for high-order stencil computations with a "
              "special focus on the requirements of multiphysics applications on modern HPC "
              "systems. It provides a multi-GPU and single-GPU APIs, a domain-specific language "
              "for expressing stencil codes in a high-level syntax, and an optimizing compiler "
              "that translates DSL sources into CUDA/HIP subroutines that exhibit near handtuned "
              "performance.";

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:astaroth_utils.h>    ////////////////////
    auto pyClassError =
        nb::class_<Error>
            (m, "Error", "")
        .def("__init__", [](Error * self, AcReal model = AcReal(), AcReal candidate = AcReal(), AcReal maximum_magnitude = AcReal(), AcReal minimum_magnitude = AcReal(), int x = int(), int y = int(), int z = int())
        {
            new (self) Error();  // placement new
            auto r_ctor_ = self;
            r_ctor_->model = model;
            r_ctor_->candidate = candidate;
            r_ctor_->maximum_magnitude = maximum_magnitude;
            r_ctor_->minimum_magnitude = minimum_magnitude;
            r_ctor_->x = x;
            r_ctor_->y = y;
            r_ctor_->z = z;
        },
        nb::arg("model") = AcReal(), nb::arg("candidate") = AcReal(), nb::arg("maximum_magnitude") = AcReal(), nb::arg("minimum_magnitude") = AcReal(), nb::arg("x") = int(), nb::arg("y") = int(), nb::arg("z") = int()
        )
        .def_rw("model", &Error::model, "")
        .def_rw("candidate", &Error::candidate, "")
        .def_rw("abs_error", &Error::abs_error, "")
        .def_rw("ulp_error", &Error::ulp_error, "")
        .def_rw("rel_error", &Error::rel_error, "")
        .def_rw("maximum_magnitude", &Error::maximum_magnitude, "")
        .def_rw("minimum_magnitude", &Error::minimum_magnitude, "")
        .def_rw("x", &Error::x, "")
        .def_rw("y", &Error::y, "")
        .def_rw("z", &Error::z, "")
        ;


    m.def("host_vertex_buffer_set",
        acHostVertexBufferSet, nb::arg("handle"), nb::arg("value"), nb::arg("mesh"));

    m.def("host_mesh_set",
        acHostMeshSet, nb::arg("value"), nb::arg("mesh"));

    m.def("host_mesh_apply_periodic_bounds",
        acHostMeshApplyPeriodicBounds, nb::arg("mesh"));

    m.def("host_mesh_apply_constant_bounds",
        acHostMeshApplyConstantBounds, nb::arg("value"), nb::arg("mesh"));

    m.def("host_mesh_clear",
        acHostMeshClear, nb::arg("mesh"));

    m.def("host_integrate_step",
        acHostIntegrateStep,
        nb::arg("mesh"), nb::arg("dt"),
        "* Applies a full integration step on host mesh using the compact 2N RK3 scheme. The boundaries are\n * not updated after the final substep. A call to acHostMeshApplyPeriodicBounds is required if this\n * is not desired. NOTE: applies boundary conditions on the mesh before the initial substep.");

    m.def("host_reduce_scal",
        acHostReduceScal, nb::arg("mesh"), nb::arg("reduction"), nb::arg("a"));

    m.def("host_reduce_vec",
        acHostReduceVec, nb::arg("mesh"), nb::arg("reduction"), nb::arg("a"), nb::arg("b"), nb::arg("c"));

    m.def("host_reduce_vec_scal",
        acHostReduceVecScal, nb::arg("mesh"), nb::arg("reduction"), nb::arg("a"), nb::arg("b"), nb::arg("c"), nb::arg("d"));

    m.def("eval_error",
        acEvalError, nb::arg("label"), nb::arg("error"));

    m.def("eval_error_with_maximum_error",
        acEvalErrorWithMaximumError, nb::arg("label"), nb::arg("error"), nb::arg("max_ulp_error"));

    m.def("verify_mesh",
        acVerifyMesh, nb::arg("label"), nb::arg("model"), nb::arg("candidate"));

    m.def("verify_mesh_with_maximum_error",
        acVerifyMeshWithMaximumError, nb::arg("label"), nb::arg("model"), nb::arg("candidate"), nb::arg("max_ulp_error"));

    m.def("mesh_diff_write_slice_z",
        acMeshDiffWriteSliceZ, nb::arg("path"), nb::arg("model"), nb::arg("candidate"), nb::arg("z"));

    m.def("mesh_diff_write",
        acMeshDiffWrite, nb::arg("path"), nb::arg("model"), nb::arg("candidate"));

    m.def("verify_mesh_comp_domain",
        acVerifyMeshCompDomain, nb::arg("label"), nb::arg("model"), nb::arg("candidate"));

    m.def("host_mesh_write_to_file",
        acHostMeshWriteToFile, nb::arg("mesh"), nb::arg("id"));

    m.def("host_mesh_read_from_file",
        acHostMeshReadFromFile, nb::arg("id"), nb::arg("mesh"));

    m.def("get_error",
        acGetError, nb::arg("model"), nb::arg("candidate"));

    m.def("host_profile_derz",
        acHostProfileDerz,
        nb::arg("in_"), nb::arg("count"), nb::arg("grid_spacing"), nb::arg("out"),
        "Profiles");

    m.def("host_profile_derzz",
        acHostProfileDerzz, nb::arg("in_"), nb::arg("count"), nb::arg("grid_spacing"), nb::arg("out"));

    m.def("host_reduce_xy_average",
        acHostReduceXYAverage, nb::arg("in_"), nb::arg("dims"), nb::arg("out"));

    m.def("host_write_profile_to_file",
        acHostWriteProfileToFile,
        nb::arg("filepath"), nb::arg("profile"), nb::arg("profile_count"),
        "* Writes the host profile to a file");

    m.def("host_init_profile_to_cosine_wave",
        acHostInitProfileToCosineWave,
        nb::arg("spacing"), nb::arg("initial_pos"), nb::arg("amplitude"), nb::arg("wavenumber"), nb::arg("mz"), nb::arg("profile"),
        "* Inits the profile to cosine wave");

    m.def("host_init_profile_to_sine_wave",
        acHostInitProfileToSineWave,
        nb::arg("spacing"), nb::arg("initial_pos"), nb::arg("amplitude"), nb::arg("wavenumber"), nb::arg("mz"), nb::arg("profile"),
        "* Inits the profile to sine wave");

    m.def("host_init_profile_to_value",
        acHostInitProfileToValue,
        nb::arg("value"), nb::arg("profile_count"), nb::arg("profile"),
        "* Initialize a profile to a constant value");

    m.def("load_config",
        acLoadConfig, nb::arg("config_path"), nb::arg("config"));
    ////////////////////    </generated_from:astaroth_utils.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
