/*
    Copyright (C) 2026 Ondřej Míchal.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/vector.h>
#include <nanobind/ndarray.h>

#include "astaroth.h"
#include "astaroth_node.h"

namespace nb = nanobind;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NB_MODULE(core, m)
{
    m.doc() = "Astaroth is a multi-GPU library designed for high-order stencil computations with a "
              "special focus on the requirements of multiphysics applications on modern HPC "
              "systems. It provides a multi-GPU and single-GPU APIs, a domain-specific language "
              "for expressing stencil codes in a high-level syntax, and an optimizing compiler "
              "that translates DSL sources into CUDA/HIP subroutines that exhibit near handtuned "
              "performance.";

    auto pyNode = nb::class_<Node>(m, "Node");

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:astaroth_node.h>    ////////////////////
    m.def("node_create",
        acNodeCreate, nb::arg("id"), nb::arg("node_config"), nb::arg("node"));

    m.def("node_destroy",
        acNodeDestroy,
        nb::arg("node"),
        "*\nResets all devices on the current node.\n\n@see acNodeCreate()\n");

    m.def("node_print_info",
        acNodePrintInfo,
        nb::arg("node"),
        "*\nPrints information about the devices available on the current node.\n\nRequires that Node has been initialized with\n@See acNodeCreate().\n");

    m.def("node_auto_optimize",
        acNodeAutoOptimize, nb::arg("node"));

    m.def("node_synchronize_stream",
        acNodeSynchronizeStream, nb::arg("node"), nb::arg("stream"));

    m.def("node_synchronize_vertex_buffer",
        acNodeSynchronizeVertexBuffer,
        nb::arg("node"), nb::arg("stream"), nb::arg("vtxbuf_handle"),
        "Not in Device");

    m.def("node_synchronize_mesh",
        acNodeSynchronizeMesh,
        nb::arg("node"), nb::arg("stream"),
        "Not in Device");

    m.def("node_swap_buffers",
        acNodeSwapBuffers, nb::arg("node"));

    m.def("node_load_constant",
        acNodeLoadConstant, nb::arg("node"), nb::arg("stream"), nb::arg("param"), nb::arg("value"));

    m.def("node_load_vertex_buffer_with_offset",
        acNodeLoadVertexBufferWithOffset,
        nb::arg("node"), nb::arg("stream"), nb::arg("host_mesh"), nb::arg("vtxbuf_handle"), nb::arg("src"), nb::arg("dst"), nb::arg("num_vertices"),
        "* Deprecated ? Might be useful though if the user wants to load only one vtxbuf. But in this case\n * the user should supply a AcReal* instead of vtxbuf_handle");

    m.def("node_load_mesh_with_offset",
        acNodeLoadMeshWithOffset, nb::arg("node"), nb::arg("stream"), nb::arg("host_mesh"), nb::arg("src"), nb::arg("dst"), nb::arg("num_vertices"));

    m.def("node_load_vertex_buffer",
        acNodeLoadVertexBuffer,
        nb::arg("node"), nb::arg("stream"), nb::arg("host_mesh"), nb::arg("vtxbuf_handle"),
        "* Deprecated ?");

    m.def("node_load_mesh",
        acNodeLoadMesh, nb::arg("node"), nb::arg("stream"), nb::arg("host_mesh"));

    m.def("node_set_vertex_buffer",
        acNodeSetVertexBuffer, nb::arg("node"), nb::arg("stream"), nb::arg("handle"), nb::arg("value"));

    m.def("node_store_vertex_buffer_with_offset",
        acNodeStoreVertexBufferWithOffset,
        nb::arg("node"), nb::arg("stream"), nb::arg("vtxbuf_handle"), nb::arg("src"), nb::arg("dst"), nb::arg("num_vertices"), nb::arg("host_mesh"),
        "* Deprecated ?");

    m.def("node_store_mesh_with_offset",
        acNodeStoreMeshWithOffset, nb::arg("node"), nb::arg("stream"), nb::arg("src"), nb::arg("dst"), nb::arg("num_vertices"), nb::arg("host_mesh"));

    m.def("node_store_vertex_buffer",
        acNodeStoreVertexBuffer, nb::arg("node"), nb::arg("stream"), nb::arg("vtxbuf_handle"), nb::arg("host_mesh"));

    m.def("node_store_mesh",
        acNodeStoreMesh, nb::arg("node"), nb::arg("stream"), nb::arg("host_mesh"));

    m.def("node_integrate_substep",
        acNodeIntegrateSubstep, nb::arg("node"), nb::arg("stream"), nb::arg("step_number"), nb::arg("start"), nb::arg("end"), nb::arg("dt"));

    m.def("node_integrate",
        acNodeIntegrate, nb::arg("node"), nb::arg("dt"));

    m.def("node_integrate_gbc",
        acNodeIntegrateGBC, nb::arg("node"), nb::arg("config"), nb::arg("dt"));

    m.def("node_periodic_boundcond_step",
        acNodePeriodicBoundcondStep, nb::arg("node"), nb::arg("stream"), nb::arg("vtxbuf_handle"));

    m.def("node_periodic_boundconds",
        acNodePeriodicBoundconds, nb::arg("node"), nb::arg("stream"));

    m.def("node_general_boundcond_step",
        acNodeGeneralBoundcondStep, nb::arg("node"), nb::arg("stream"), nb::arg("vtxbuf_handle"), nb::arg("config"));

    m.def("node_general_boundconds",
        acNodeGeneralBoundconds, nb::arg("node"), nb::arg("stream"), nb::arg("config"));

    m.def("node_reduce_scal",
        acNodeReduceScal, nb::arg("node"), nb::arg("stream"), nb::arg("reduction"), nb::arg("vtxbuf_handle"), nb::arg("result"));

    m.def("node_reduce_vec",
        acNodeReduceVec, nb::arg("node"), nb::arg("stream_type"), nb::arg("reduction"), nb::arg("vtxbuf0"), nb::arg("vtxbuf1"), nb::arg("vtxbuf2"), nb::arg("result"));

    m.def("node_reduce_vec_scal",
        acNodeReduceVecScal, nb::arg("node"), nb::arg("stream_type"), nb::arg("reduction"), nb::arg("vtxbuf0"), nb::arg("vtxbuf1"), nb::arg("vtxbuf2"), nb::arg("vtxbuf3"), nb::arg("result"));

    m.def("node_load_plate",
        acNodeLoadPlate, nb::arg("node"), nb::arg("stream"), nb::arg("start"), nb::arg("end"), nb::arg("host_mesh"), nb::arg("plate_buffer"), nb::arg("plate"));

    m.def("node_store_plate",
        acNodeStorePlate, nb::arg("node"), nb::arg("stream"), nb::arg("start"), nb::arg("end"), nb::arg("host_mesh"), nb::arg("plate_buffer"), nb::arg("plate"));

    m.def("node_store_ixy_plate",
        acNodeStoreIXYPlate, nb::arg("node"), nb::arg("stream"), nb::arg("start"), nb::arg("end"), nb::arg("host_mesh"), nb::arg("plate"));

    m.def("node_load_plate_xcomp",
        acNodeLoadPlateXcomp, nb::arg("node"), nb::arg("stream"), nb::arg("start"), nb::arg("end"), nb::arg("host_mesh"), nb::arg("plate_buffer"), nb::arg("plate"));
    ////////////////////    </generated_from:astaroth_node.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
