/*
    Copyright (C) 2026 Ondřej Míchal.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <nanobind/nanobind.h>
#include <nanobind/stl/array.h>
#include <nanobind/stl/function.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/vector.h>
#include <nanobind/ndarray.h>

#include "astaroth.h"

namespace nb = nanobind;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NB_MODULE(core, m)
{
    m.doc() = "Astaroth is a multi-GPU library designed for high-order stencil computations with a "
              "special focus on the requirements of multiphysics applications on modern HPC "
              "systems. It provides a multi-GPU and single-GPU APIs, a domain-specific language "
              "for expressing stencil codes in a high-level syntax, and an optimizing compiler "
              "that translates DSL sources into CUDA/HIP subroutines that exhibit near handtuned "
              "performance.";

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:astaroth_legacy.h>    ////////////////////
    m.def("init",
        acInit,
        nb::arg("mesh_info"),
        "* Allocates all memory and initializes the devices visible to the caller. Should be\n * called before any other function in this interface.");

    m.def("quit",
        acQuit, "* Frees all GPU allocations and resets all devices in the node. Should be\n * called at exit.");

    m.def("synchronize_stream",
        acSynchronizeStream,
        nb::arg("stream"),
        "* Synchronizes a specific stream. All streams are synchronized if STREAM_ALL is passed as a\n * parameter");

    m.def("synchronize_mesh",
        acSynchronizeMesh);

    m.def("load_device_constant",
        acLoadDeviceConstant,
        nb::arg("param"), nb::arg("value"),
        "* Loads a constant to the memories of the devices visible to the caller");

    m.def("load",
        acLoad,
        nb::arg("host_mesh"),
        "* Loads an AcMesh to the devices visible to the caller");

    m.def("set_vertex_buffer",
        acSetVertexBuffer,
        nb::arg("handle"), nb::arg("value"),
        "* Sets the whole mesh to some value");

    m.def("store",
        acStore,
        nb::arg("host_mesh"),
        "* Stores the AcMesh distributed among the devices visible to the caller back to the host");

    m.def("integrate",
        acIntegrate,
        nb::arg("dt"),
        "* Performs Runge-Kutta 3 integration. Note: Boundary conditions are not applied after the final\n * substep and the user is responsible for calling acBoundcondStep before reading the data.");

    m.def("integrate_gbc",
        acIntegrateGBC,
        nb::arg("config"), nb::arg("dt"),
        "* Performs Runge-Kutta 3 integration. Note: Boundary conditions are not applied after the final\n * substep and the user is responsible for calling acBoundcondStep before reading the data.\n * Has customizable boundary conditions.");

    m.def("boundcond_step",
        acBoundcondStep, "* Applies periodic boundary conditions for the Mesh distributed among the devices visible to\n * the caller");

    m.def("boundcond_step_gbc",
        acBoundcondStepGBC,
        nb::arg("config"),
        "* Applies general outer boundary conditions for the Mesh distributed among the devices visible to\n * the caller");

    m.def("reduce_scal",
        acReduceScal,
        nb::arg("reduction"), nb::arg("vtxbuf_handle"),
        "* Does a scalar reduction with the data stored in some vertex buffer");

    m.def("reduce_vec",
        acReduceVec,
        nb::arg("reduction"), nb::arg("a"), nb::arg("b"), nb::arg("c"),
        "* Does a vector reduction with vertex buffers where the vector components are (a, b, c)");

    m.def("reduce_vec_scal",
        acReduceVecScal,
        nb::arg("reduction"), nb::arg("a"), nb::arg("b"), nb::arg("c"), nb::arg("d"),
        "* Does a reduction for an operation which requires a vector and a scalar with vertex buffers\n *  * where the vector components are (a, b, c) and scalr is (d)");

    m.def("store_with_offset",
        acStoreWithOffset,
        nb::arg("dst"), nb::arg("num_vertices"), nb::arg("host_mesh"),
        "* Stores a subset of the mesh stored across the devices visible to the caller back to host memory.\n");

    m.def("integrate_step",
        acIntegrateStep, nb::arg("isubstep"), nb::arg("dt"));

    m.def("integrate_step_with_offset",
        acIntegrateStepWithOffset, nb::arg("isubstep"), nb::arg("dt"), nb::arg("start"), nb::arg("end"));

    m.def("synchronize",
        acSynchronize);

    m.def("load_with_offset",
        acLoadWithOffset, nb::arg("host_mesh"), nb::arg("src"), nb::arg("num_vertices"));

    m.def("check_device_availability",
        acCheckDeviceAvailability);

    m.def("get_num_devices_per_node",
        acGetNumDevicesPerNode);

    m.def("get_num_fields",
        acGetNumFields, "* Returns the number of fields (vertexbuffer handles).");

    m.def("get_field_handle",
        acGetFieldHandle, nb::arg("field"), nb::arg("handle"));

    m.def("get_field_name",
        acGetFieldName, nb::arg("field"));
    ////////////////////    </generated_from:astaroth_legacy.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
