var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "ac_fft.h", "ac__fft_8h.html", "ac__fft_8h" ],
    [ "ac_helpers.h", "ac__helpers_8h.html", "ac__helpers_8h" ],
    [ "ac_mpi.h", "ac__mpi_8h.html", null ],
    [ "astaroth.h", "astaroth_8h.html", "astaroth_8h" ],
    [ "astaroth_analysis_helpers.h", "astaroth__analysis__helpers_8h.html", "astaroth__analysis__helpers_8h" ],
    [ "astaroth_base.h", "astaroth__base_8h.html", "astaroth__base_8h" ],
    [ "astaroth_cuda_wrappers.h", "astaroth__cuda__wrappers_8h.html", "astaroth__cuda__wrappers_8h" ],
    [ "astaroth_debug.h", "astaroth__debug_8h.html", null ],
    [ "astaroth_device.h", "astaroth__device_8h.html", "astaroth__device_8h" ],
    [ "astaroth_forcing.h", "astaroth__forcing_8h.html", "astaroth__forcing_8h" ],
    [ "astaroth_grid.h", "astaroth__grid_8h.html", "astaroth__grid_8h" ],
    [ "astaroth_helpers.h", "astaroth__helpers_8h.html", "astaroth__helpers_8h" ],
    [ "astaroth_legacy.h", "astaroth__legacy_8h.html", "astaroth__legacy_8h" ],
    [ "astaroth_lib.h", "astaroth__lib_8h.html", "astaroth__lib_8h" ],
    [ "astaroth_logging.h", "astaroth__logging_8h.html", "astaroth__logging_8h" ],
    [ "astaroth_node.h", "astaroth__node_8h.html", "astaroth__node_8h" ],
    [ "astaroth_random.h", "astaroth__random_8h.html", "astaroth__random_8h" ],
    [ "astaroth_runtime_compilation.h", "astaroth__runtime__compilation_8h.html", "astaroth__runtime__compilation_8h" ],
    [ "astaroth_utils.h", "astaroth__utils_8h.html", "astaroth__utils_8h" ],
    [ "device_detail.h", "device__detail_8h.html", "device__detail_8h" ],
    [ "func_define.h", "func__define_8h.html", "func__define_8h" ],
    [ "grid_detail.h", "grid__detail_8h.html", null ],
    [ "timer_hires.h", "timer__hires_8h.html", "timer__hires_8h" ]
];