var hierarchy =
[
    [ "acAnalysisBCInfo", "structacAnalysisBCInfo.html", null ],
    [ "AcAutotuneMeasurement", "structAcAutotuneMeasurement.html", null ],
    [ "AcBuffer", "structAcBuffer.html", null ],
    [ "AcCommunicator", "structAcCommunicator.html", null ],
    [ "AcCompInfo", "structAcCompInfo.html", null ],
    [ "AcCompInfoConfig", "structAcCompInfoConfig.html", null ],
    [ "AcCompInfoHasDefaultValue", "structAcCompInfoHasDefaultValue.html", null ],
    [ "AcCompInfoLoaded", "structAcCompInfoLoaded.html", null ],
    [ "AcComplexFloatInAndOut", "structAcComplexFloatInAndOut.html", null ],
    [ "AcComplexInAndOut", "structAcComplexInAndOut.html", null ],
    [ "AcDecompositionInfo", "structAcDecompositionInfo.html", null ],
    [ "AcDeviceKernelOutput", "structAcDeviceKernelOutput.html", null ],
    [ "AcDeviceTmpBuffer", "structAcDeviceTmpBuffer.html", null ],
    [ "AcGridInfo", "structAcGridInfo.html", null ],
    [ "AcInputs", "structAcInputs.html", null ],
    [ "AcMesh", "structAcMesh.html", null ],
    [ "AcMeshDims", "structAcMeshDims.html", null ],
    [ "AcMeshInfo", "structAcMeshInfo.html", null ],
    [ "AcMeshInfoLoaded", "structAcMeshInfoLoaded.html", null ],
    [ "AcMeshInfoScalars", "structAcMeshInfoScalars.html", null ],
    [ "AcReduceBuffer", "structAcReduceBuffer.html", null ],
    [ "AcReduction", "structAcReduction.html", null ],
    [ "AcScratchpadStates", "structAcScratchpadStates.html", null ],
    [ "AcShape", "structAcShape.html", null ],
    [ "AcShearInterpolationCoeffs", "structAcShearInterpolationCoeffs.html", null ],
    [ "AcSubCommunicators", "structAcSubCommunicators.html", null ],
    [ "AcTaskDefinition", "structAcTaskDefinition.html", null ],
    [ "AcTaskGraph", "structAcTaskGraph.html", null ],
    [ "allocate_arrays< P >", "structallocate__arrays.html", null ],
    [ "array_info", "structarray__info.html", null ],
    [ "astnode_s", "structastnode__s.html", null ],
    [ "bc_fields", "structbc__fields.html", null ],
    [ "BoundCond", "structBoundCond.html", null ],
    [ "CodeGenInput", "structCodeGenInput.html", null ],
    [ "combinatorial_params", "structcombinatorial__params.html", null ],
    [ "combinatorial_params_info", "structcombinatorial__params__info.html", null ],
    [ "CommData", "structCommData.html", null ],
    [ "CrossProductInputs", "structCrossProductInputs.html", null ],
    [ "device_s", "structdevice__s.html", null ],
    [ "DeviceConfiguration", "structDeviceConfiguration.html", null ],
    [ "DeviceVertexBufferArray", "structDeviceVertexBufferArray.html", null ],
    [ "dfunc_possibilities", "structdfunc__possibilities.html", null ],
    [ "Error", "structError.html", null ],
    [ "facet_class_range", "structfacet__class__range.html", null ],
    [ "ForcingParams", "structForcingParams.html", null ],
    [ "free_arrays< P >", "structfree__arrays.html", null ],
    [ "func_params_info", "structfunc__params__info.html", null ],
    [ "funcs_calling_info", "structfuncs__calling__info.html", null ],
    [ "gen_constexpr_params", "structgen__constexpr__params.html", null ],
    [ "GpuVtxBufHandles", "structGpuVtxBufHandles.html", null ],
    [ "Grid", "structGrid.html", null ],
    [ "GridDims", "structGridDims.html", null ],
    [ "HaloMessage", "structHaloMessage.html", null ],
    [ "HaloMessageSwapChain", "structHaloMessageSwapChain.html", null ],
    [ "hashmap_create_options_s", "structhashmap__create__options__s.html", null ],
    [ "hashmap_element_s", "structhashmap__element__s.html", null ],
    [ "hashmap_s", "structhashmap__s.html", null ],
    [ "int3", "structint3.html", null ],
    [ "Int3Hash", "structInt3Hash.html", null ],
    [ "int_vec", "structint__vec.html", null ],
    [ "KernelAnalysisInfo", "structKernelAnalysisInfo.html", null ],
    [ "KernelCall", "structKernelCall.html", null ],
    [ "KernelFields", "structKernelFields.html", null ],
    [ "KernelOutputs", "structKernelOutputs.html", null ],
    [ "KernelParameters", "structKernelParameters.html", null ],
    [ "KernelProfiles", "structKernelProfiles.html", null ],
    [ "KernelReduceOutput", "structKernelReduceOutput.html", null ],
    [ "KernelReduceOutputs", "structKernelReduceOutputs.html", null ],
    [ "KeyEqual", "structKeyEqual.html", null ],
    [ "KeyHash", "structKeyHash.html", null ],
    [ "kiss_fft_cpx", "structkiss__fft__cpx.html", null ],
    [ "kiss_fft_state", "structkiss__fft__state.html", null ],
    [ "kiss_fftnd_state", "structkiss__fftnd__state.html", null ],
    [ "level_set", "structlevel__set.html", null ],
    [ "load_all_arrays_uniform< P >", "structload__all__arrays__uniform.html", null ],
    [ "load_all_scalars_uniform< P >", "structload__all__scalars__uniform.html", null ],
    [ "load_arrays< P >", "structload__arrays.html", null ],
    [ "load_comp_arrays< P >", "structload__comp__arrays.html", null ],
    [ "load_comp_scalars< P >", "structload__comp__scalars.html", null ],
    [ "load_scalars< P >", "structload__scalars.html", null ],
    [ "LoadKernelParamsFunc", "structLoadKernelParamsFunc.html", null ],
    [ "node_vec", "structnode__vec.html", null ],
    [ "op_vec", "structop__vec.html", null ],
    [ "overloaded_dfuncs", "structoverloaded__dfuncs.html", null ],
    [ "param_combinations", "structparam__combinations.html", null ],
    [ "ParamLoadingInfo", "structParamLoadingInfo.html", null ],
    [ "ProfileBufferArray", "structProfileBufferArray.html", null ],
    [ "Region", "structRegion.html", null ],
    [ "RegionMemory", "structRegionMemory.html", null ],
    [ "RegionMemoryInputParams", "structRegionMemoryInputParams.html", null ],
    [ "safe_array< T >", "structsafe__array.html", null ],
    [ "size_t2", "structsize__t2.html", null ],
    [ "size_t2Hash", "structsize__t2Hash.html", null ],
    [ "SOAVector", "structSOAVector.html", null ],
    [ "state", "structstate.html", null ],
    [ "string_vec", "structstring__vec.html", null ],
    [ "structs_info", "structstructs__info.html", null ],
    [ "Symbol", "structSymbol.html", null ],
    [ "Task", "classTask.html", [
      [ "BoundaryConditionTask", "classBoundaryConditionTask.html", null ],
      [ "ComputeTask", "classComputeTask.html", null ],
      [ "HaloExchangeTask", "classHaloExchangeTask.html", null ],
      [ "MPIScanTask", "classMPIScanTask.html", null ],
      [ "PeriodicRayTask", "classPeriodicRayTask.html", null ],
      [ "ReduceTask", "classReduceTask.html", null ]
    ] ],
    [ "TBConfig", "structTBConfig.html", null ],
    [ "te_expr", "structte__expr.html", null ],
    [ "te_variable", "structte__variable.html", null ],
    [ "TraceFile", "structTraceFile.html", null ],
    [ "traverse_base_params", "structtraverse__base__params.html", null ],
    [ "tspecifier", "structtspecifier.html", null ],
    [ "uint2_64", "structuint2__64.html", null ],
    [ "uint3_64", "structuint3__64.html", null ],
    [ "update_arrays< P >", "structupdate__arrays.html", null ],
    [ "user_enums_info", "structuser__enums__info.html", null ],
    [ "variable", "structvariable.html", null ],
    [ "VectorHash", "structVectorHash.html", null ],
    [ "VertexBufferArray", "structVertexBufferArray.html", null ],
    [ "Volume", "structVolume.html", null ],
    [ "VolumeHash", "structVolumeHash.html", null ]
];