#!/bin/bash
#
cmake -B build -S $AC_HOME -DRUNTIME_COMPILATION=ON -DOPTIMIZE_INPUT_PARAMS=ON -DOPTIMIZE_MEM_ACCESSES=ON -DCMAKE_BUILD_TYPE=Release -DDSL_MODULE_DIR="$AC_HOME/acc-runtime/samples/mhd_modular" -DBUILD_UTILS=ON -DBUILD_SAMPLES=ON -DDOUBLE_PRECISION=ON -DMULTIGPU_ENABLED=ON -DMPI_ENABLED=ON -DBUILD_ACM=ON -DCPU_BUILD=ON && cmake --build build -j
