#!/bin/bash
#
mkdir -p build && cd build && cmake -DOPTIMIZE_MEM_ACCESSES=ON -DUSE_HIP=OFF -DCMAKE_BUILD_TYPE=Release -DDSL_MODULE_DIR="$AC_HOME/acc-runtime/samples/mhd_modular" -DBUILD_UTILS=ON -DBUILD_SAMPLES=ON -DDOUBLE_PRECISION=ON -DMULTIGPU_ENABLED=ON -DMPI_ENABLED=ON -DBUILD_ACM=ON -DCPU_BUILD=ON $AC_HOME && make -j
