#!/bin/bash
#
mkdir -p build && cd build && cmake -DMPI_ENABLED=ON -DFFT_ENABLED=OFF -DAC_STENCIL_ORDER=6 -DOPTIMIZE_MEM_ACCESSES=ON -DBUILD_TESTS=ON -DRUNTIME_COMPILATION=OFF -DDSL_MODULE_DIR=../DSL $AC_HOME && make compact-poisson-test -j
