#!/bin/bash
#
cmake -B build -S $AC_HOME -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-DPENCIL_A" -DOPTIMIZE_INPUT_PARAMS=ON -DOPTIMIZE_FIELDS=ON -DUSE_ONLY_OPTIMIZED_KERNELS=ON -DOPTIMIZE_ARRAYS=ON -DOPTIMIZE_MEM_ACCESSES=ON -DBUILD_TESTS=OFF -DRUNTIME_COMPILATION=ON -DALLOW_DEAD_VARIABLES=ON -DDSL_MODULE_DIR=$AC_HOME/PencilA-setups/Coala/code/DSL/local -DDSL_MODULE_FILE=solve.ac && cmake --build build -t ac_run_mpi -j
