name: 'Build and test an Astaroth build'
description: 'Builds and tests an Astaroth build using scripts in the given build configuration.'

inputs:
  build-configuration-dir:
    description: 'Path to a directory with an Astaroth build and test configuration.'
    required: true

runs:
  using: "composite"

  steps:
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        key: ${{ runner.os }}-${{ github.job }}-${{ inputs.build-configuration-dir }}
        max-size: 50MB

    - name: Run build.sh script
      shell: bash
      run: |
        echo "::group::Build Astaroth project"
        if [ -f "$GITHUB_WORKSPACE/${{ inputs.build-configuration-dir }}/build.sh" ]; then
          source sourceme.sh
          cd $GITHUB_WORKSPACE/${{ inputs.build-configuration-dir }}
          ./build.sh
        fi
        echo "::endgroup::"
      env:
        OMPI_ALLOW_RUN_AS_ROOT: 1
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

    - name: Run run.sh script (if present)
      shell: bash
      run: |
        echo "::group::Test Astaroth project"
        if [ -f "$GITHUB_WORKSPACE/${{ inputs.build-configuration-dir }}/run.sh" ]; then
          source sourceme.sh
          cd $GITHUB_WORKSPACE/${{ inputs.build-configuration-dir }}
          ./run.sh
        fi
        echo "::endgroup::"
      env:
        OMPI_ALLOW_RUN_AS_ROOT: 1
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
