name: 'Build and test an Astaroth build'
description: 'Builds and tests an Astaroth build using scripts in the given build configuration.'

inputs:
  build-configuration-dir:
    description: 'Path to a directory with an Astaroth build.sh script'
    required: true

runs:
  using: "composite"

  steps:
    - name: Run build.sh script
      run: |
        source sourceme.sh
        cd ${{ inputs.build-configuration-dir }}
        ./build.sh
      env:
        OMPI_ALLOW_RUN_AS_ROOT: 1
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

    - name: Run test.sh script (if present)
      run: |
        if [ -f "${{ inputs.build-configuration-dir }}/test.sh" ]; then
          source sourceme.sh
          cd ${{ inputs.build-configuration-dir }}
          ./test.sh
        fi
      env:
        OMPI_ALLOW_RUN_AS_ROOT: 1
        OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
