#!/bin/bash
#
mkdir -p build && cd build && cmake -DALLOW_DEAD_VARIABLES=ON -DMPI_ENABLED=ON -DAC_STENCIL_ORDER=6 -DFFT_ENABLED=OFF -DOPTIMIZE_MEM_ACCESSES=ON -DBUILD_TESTS=ON -DRUNTIME_COMPILATION=OFF -DDSL_MODULE_DIR=../DSL $AC_HOME && make iterative-refinement-test -j
