# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub>  // Autogenerated code below! Do not edit!
####################    <generated_from:astaroth_legacy.h>    ####################


def init(mesh_info: AcMeshInfo) -> AcResult:
    """* Allocates all memory and initializes the devices visible to the caller. Should be
     * called before any other function in this interface.
    """
    pass

def quit() -> AcResult:
    """* Frees all GPU allocations and resets all devices in the node. Should be
     * called at exit.
    """
    pass

def synchronize_stream(stream: Stream) -> AcResult:
    """* Synchronizes a specific stream. All streams are synchronized if STREAM_ALL is passed as a
     * parameter
    """
    pass

def synchronize_mesh() -> AcResult:
    pass

def load_device_constant(param: AcRealParam, value: AcReal) -> AcResult:
    """* Loads a constant to the memories of the devices visible to the caller"""
    pass

def load(host_mesh: AcMesh) -> AcResult:
    """* Loads an AcMesh to the devices visible to the caller"""
    pass

def set_vertex_buffer(handle: VertexBufferHandle, value: AcReal) -> AcResult:
    """* Sets the whole mesh to some value"""
    pass

def store(host_mesh: AcMesh) -> AcResult:
    """* Stores the AcMesh distributed among the devices visible to the caller back to the host"""
    pass

def integrate(dt: AcReal) -> AcResult:
    """* Performs Runge-Kutta 3 integration. Note: Boundary conditions are not applied after the final
     * substep and the user is responsible for calling acBoundcondStep before reading the data.
    """
    pass

def integrate_gbc(config: AcMeshInfo, dt: AcReal) -> AcResult:
    """* Performs Runge-Kutta 3 integration. Note: Boundary conditions are not applied after the final
     * substep and the user is responsible for calling acBoundcondStep before reading the data.
     * Has customizable boundary conditions.
    """
    pass

def boundcond_step() -> AcResult:
    """* Applies periodic boundary conditions for the Mesh distributed among the devices visible to
     * the caller
    """
    pass

def boundcond_step_gbc(config: AcMeshInfo) -> AcResult:
    """* Applies general outer boundary conditions for the Mesh distributed among the devices visible to
     * the caller
    """
    pass

def reduce_scal(reduction: AcReduction, vtxbuf_handle: VertexBufferHandle) -> AcReal:
    """* Does a scalar reduction with the data stored in some vertex buffer"""
    pass

def reduce_vec(
    reduction: AcReduction,
    a: VertexBufferHandle,
    b: VertexBufferHandle,
    c: VertexBufferHandle
    ) -> AcReal:
    """* Does a vector reduction with vertex buffers where the vector components are (a, b, c)"""
    pass

def reduce_vec_scal(
    reduction: AcReduction,
    a: VertexBufferHandle,
    b: VertexBufferHandle,
    c: VertexBufferHandle,
    d: VertexBufferHandle
    ) -> AcReal:
    """* Does a reduction for an operation which requires a vector and a scalar with vertex buffers
     *  * where the vector components are (a, b, c) and scalr is (d)
    """
    pass

def store_with_offset(dst: int3, num_vertices: int, host_mesh: AcMesh) -> AcResult:
    """* Stores a subset of the mesh stored across the devices visible to the caller back to host memory.

    """
    pass

#* Will potentially be deprecated in later versions. Added only to fix backwards compatibility with
# * PC for now.
def integrate_step(isubstep: int, dt: AcReal) -> AcResult:
    pass
def integrate_step_with_offset(
    isubstep: int,
    dt: AcReal,
    start: Volume,
    end: Volume
    ) -> AcResult:
    pass
def synchronize() -> AcResult:
    pass
def load_with_offset(host_mesh: AcMesh, src: int3, num_vertices: int) -> AcResult:
    pass


def check_device_availability() -> AcResult:
    pass

def get_num_devices_per_node() -> int:
    pass

def get_num_fields() -> int:
    """* Returns the number of fields (vertexbuffer handles)."""
    pass

#* Gets the field handle corresponding to a null-terminated `str` and stores the result in
# * `handle`.
# *
# * Returns AC_SUCCESS on success.
# * Returns AC_FAILURE if the field was not found and sets `handle` to SIZE_MAX.
# *
# * Example usage:
# * ```C
# * size_t handle;
# * AcResult res = acGetFieldHandle("VTXBUF_LNRHO", &handle);
# * if (res != AC_SUCCESS)
# *  fprintf(stderr, "Handle not found\n");
# * ```
# *
def get_field_handle(field: str, handle: int) -> AcResult:
    pass
def get_field_name(field: Field) -> str:
    pass####################    </generated_from:astaroth_legacy.h>    ####################

# </litgen_stub> // Autogenerated code end
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
