  const AcReduction RTYPE_MAX = {REDUCE_MAX,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF,AC_MAP_VTXBUF3_NORM,AC_NULL_KERNEL,"RTYPE_MAX"};
  const AcReduction RTYPE_MIN = {REDUCE_MIN,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF,AC_MAP_VTXBUF3_NORM,AC_NULL_KERNEL,"RTYPE_MIN"};
  const AcReduction RTYPE_SUM =	{REDUCE_SUM,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF,AC_MAP_VTXBUF3_NORM,AC_NULL_KERNEL,"RTYPE_SUM"};
  const AcReduction RTYPE_RMS = {REDUCE_SUM,AC_RMS,AC_MAP_VTXBUF_SQUARE,AC_MAP_VTXBUF3_SQUARE,AC_NULL_KERNEL,"RTYPE_RMS"};
  const AcReduction RTYPE_RMS_EXP = {REDUCE_SUM,AC_RMS,AC_MAP_VTXBUF_EXP_SQUARE,AC_MAP_VTXBUF3_EXP_SQUARE,AC_NULL_KERNEL,"RTYPE_RMS_EXP"};
  const AcReduction RTYPE_ALFVEN_MAX = {REDUCE_MAX,AC_NO_REDUCE_POST_PROCESSING,AC_NULL_KERNEL,AC_NULL_KERNEL,AC_MAP_VTXBUF4_ALFVEN_NORM,"RTYPE_ALFVEN_MAX"};
  const AcReduction RTYPE_ALFVEN_MIN = {REDUCE_MIN,AC_NO_REDUCE_POST_PROCESSING,AC_NULL_KERNEL,AC_NULL_KERNEL,AC_MAP_VTXBUF4_ALFVEN_NORM,"RTYPE_ALFVEN_MIN"};
  const AcReduction RTYPE_ALFVEN_RMS = {REDUCE_SUM,AC_RMS,AC_NULL_KERNEL,AC_NULL_KERNEL,AC_MAP_VTXBUF4_ALFVEN_SQUARE,"RTYPE_ALFVEN_MIN"};

#ifdef AC_INTEGRATION_ENABLED
  const AcReduction RTYPE_ALFVEN_RADIAL_WINDOW_MAX = {REDUCE_MAX,AC_NO_REDUCE_POST_PROCESSING,AC_NULL_KERNEL,AC_NULL_KERNEL,AC_MAP_VTXBUF4_ALFVEN_NORM_RADIAL_WINDOW,"RTYPE_ALFVEN_RADIAL_WINDOW_MAX"};
  const AcReduction RTYPE_ALFVEN_RADIAL_WINDOW_MIN = {REDUCE_MIN,AC_NO_REDUCE_POST_PROCESSING,AC_NULL_KERNEL,AC_NULL_KERNEL,AC_MAP_VTXBUF4_ALFVEN_NORM_RADIAL_WINDOW,"RTYPE_ALFVEN_RADIAL_WINDOW_MIN"};
  const AcReduction RTYPE_ALFVEN_RADIAL_WINDOW_SUM = {REDUCE_SUM,AC_RADIAL_WINDOW_RMS,AC_NULL_KERNEL,AC_NULL_KERNEL,AC_MAP_VTXBUF4_ALFVEN_SQUARE_RADIAL_WINDOW,"RTYPE_ALFVEN_RADIAL_WINDOW_SUM"};

  const AcReduction RTYPE_RADIAL_WINDOW_MIN = {REDUCE_MAX,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF_RADIAL_WINDOW,AC_MAP_VTXBUF3_NORM_RADIAL_WINDOW,AC_NULL_KERNEL,"RTYPE_RADIAL_WINDOW_MIN"};
  const AcReduction RTYPE_RADIAL_WINDOW_MAX = {REDUCE_MIN,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF_RADIAL_WINDOW,AC_MAP_VTXBUF3_NORM_RADIAL_WINDOW,AC_NULL_KERNEL,"RTYPE_RADIAL_WINDOW_MAX"};
  const AcReduction RTYPE_RADIAL_WINDOW_SUM = {REDUCE_SUM,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF_RADIAL_WINDOW,AC_MAP_VTXBUF3_NORM_RADIAL_WINDOW,AC_NULL_KERNEL,"RTYPE_RADIAL_WINDOW_SUM"};

  const AcReduction RTYPE_GAUSSIAN_WINDOW_MAX = {REDUCE_MAX,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF_GAUSSIAN_WINDOW,AC_MAP_VTXBUF3_NORM_GAUSSIAN_WINDOW,AC_NULL_KERNEL,"RTYPE_GAUSSIAN_WINDOW_MAX"};
  const AcReduction RTYPE_GAUSSIAN_WINDOW_MIN = {REDUCE_MIN,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF_GAUSSIAN_WINDOW,AC_MAP_VTXBUF3_NORM_GAUSSIAN_WINDOW,AC_NULL_KERNEL,"RTYPE_GAUSSIAN_WINDOW_MIN"};
  const AcReduction RTYPE_GAUSSIAN_WINDOW_SUM = {REDUCE_SUM,AC_NO_REDUCE_POST_PROCESSING,AC_MAP_VTXBUF_GAUSSIAN_WINDOW,AC_MAP_VTXBUF3_NORM_GAUSSIAN_WINDOW,AC_NULL_KERNEL,"RTYPE_GAUSSIAN_WINDOW_SUM"};

#endif
