#!/bin/bash
#
cmake -B 2d-build -S $AC_HOME -DCMAKE_BUILD_TYPE=Debug -DMPI_ENABLED=ON -DOPTIMIZE_MEM_ACCESSES=ON -D2D=ON -DLAGRANGIAN_GRID=ON -DBUILD_TESTS=ON -DDSL_MODULE_DIR=../DSL/2D && cmake --build 2d-build -t planetest -j
cmake -B 3d-build -S $AC_HOME -DCMAKE_BUILD_TYPE=Debug -DMPI_ENABLED=ON -DOPTIMIZE_MEM_ACCESSES=ON -D2D=OFF -DLAGRANGIAN_GRID=ON -DBUILD_TESTS=ON -DDSL_MODULE_DIR=../DSL/3D && cmake --build 3d-build -t planetest -j
