// Generated by Pencil Code build, yet meant to be edited by the user.
// All needed rhs functions are provided, but unneeded ones are not removed.


#if LDENSITY
dlnrho_dt(int step_num){
    suppress_unused_warning(step_num)
    return 0.
}
#endif

#if LDUSTDENSITY
dndmd_dt(int step_num){
    suppress_unused_warning(step_num)
    return 0.
}
#endif

#if LDUSTVELOCITY
duud_dt(int step_num){
    suppress_unused_warning(step_num)
    return 0.
}
#endif

