#!/bin/bash
#
cmake -B build -S $AC_HOME -DRUNTIME_COMPILATION=OFF -DMAX_THREADS_PER_BLOCK=512 -DMPI_ENABLED=ON -DOPTIMIZE_MEM_ACCESSES=ON -DBUILD_TESTS=ON -DDSL_MODULE_DIR=../DSL && cmake --build build -t ray-test -j
