# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub>  // Autogenerated code below! Do not edit!
####################    <generated_from:astaroth_device.h>    ####################






# AcResult acDeviceAutoOptimize(const Device device);


































































# #ifdef __cplusplus
#









# #endif
#
####################    </generated_from:astaroth_device.h>    ####################

# </litgen_stub> // Autogenerated code end
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
