# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub>  // Autogenerated code below! Do not edit!
####################    <generated_from:astaroth_grid.h>    ####################



# #if AC_MPI_ENABLED
#
def mpi_init() -> AcResult:
    """*
    Calls MPI_Init and creates a separate communicator for Astaroth procs with MPI_Comm_split, color =
    666 Any program running in the same MPI process space must also call MPI_Comm_split with some color
    != 666. OTHERWISE this call will hang.

    Returns AC_SUCCESS on successfullly initializing MPI and creating a communicator.

    Returns AC_FAILURE otherwise.

    """
    pass

def mpi_init_thread(thread_level: int) -> AcResult:
    """*
    Calls MPI_Init_thread with the provided thread_level and creates a separate communicator for
    Astaroth procs with MPI_Comm_split, color = 666 Any program running in the same MPI process space
    must also call MPI_Comm_split with some color != 666. OTHERWISE this call will hang.

    Returns AC_SUCCESS on successfullly initializing MPI with the requested thread level and creating a
    communicator.

    Returns AC_FAILURE otherwise.

    """
    pass

def mpi_finalize() -> None:
    """*
    Destroys the communicator and calls MPI_Finalize

    """
    pass

def mpi_comm_rank() -> int:
    """* Returns the rank of the Astaroth communicator"""
    pass


def grid_mpi_sub_comms() -> AcSubCommunicators:
    pass
def mpi_comm_size() -> int:
    """* Returns the size of the Astaroth communicator"""
    pass

def mpi_barrier() -> None:
    """* Calls MPI_Barrier on the Astaroth communicator"""
    pass

#*
#Initializes all available devices.
#
#Must compile and run the code with MPI.
#
#Must allocate exactly one process per GPU. And the same number of processes
#per node as there are GPUs on that node.
#
#Devices in the grid are configured based on the contents of AcMesh.
#

def grid_init_base(mesh: AcMesh) -> AcResult:
    pass
@overload
def grid_init(info: AcMeshInfo) -> AcResult:
    pass
@overload
def grid_init(mesh: AcMesh) -> AcResult:
    pass

def grid_quit() -> AcResult:
    """*
    Resets all devices on the current grid.

    """
    pass


def grid_randomize() -> AcResult:
    """* Randomizes the local mesh"""
    pass

def grid_synchronize_stream(stream: Stream) -> AcResult:
    pass

def grid_load_scalar_uniform(
    stream: Stream,
    param: AcRealParam,
    value: AcReal
    ) -> AcResult:
    pass

def grid_load_vector_uniform(
    stream: Stream,
    param: AcReal3Param,
    value: AcReal3
    ) -> AcResult:
    pass

def grid_load_int_uniform(stream: Stream, param: AcIntParam, value: int) -> AcResult:
    pass

def grid_load_int3_uniform(
    stream: Stream,
    param: AcInt3Param,
    value: int3
    ) -> AcResult:
    pass

def grid_load_mesh(stream: Stream, host_mesh: AcMesh) -> AcResult:
    pass

def grid_store_mesh(stream: Stream, host_mesh: AcMesh) -> AcResult:
    pass

def grid_integrate(stream: Stream, dt: AcReal) -> AcResult:
    pass

def grid_swap_buffers() -> AcResult:
    pass

#   MV: Commented out for a while, but save for the future when standalone_MPI
#         works with periodic boundary conditions.
#AcResult
#acGridIntegrateNonperiodic(const Stream stream, const AcReal dt)
#
#AcResult acGridIntegrateNonperiodic(const Stream stream, const AcReal dt);
#

def grid_halo_exchange() -> AcResult:
    pass

def grid_periodic_boundconds(stream: Stream) -> AcResult:
    pass


def grid_reduce_scal(
    stream: Stream,
    reduction: AcReduction,
    vtxbuf_handle: VertexBufferHandle,
    result: AcReal
    ) -> AcResult:
    pass

def grid_reduce_vec(
    stream: Stream,
    reduction: AcReduction,
    vtxbuf0: VertexBufferHandle,
    vtxbuf1: VertexBufferHandle,
    vtxbuf2: VertexBufferHandle,
    result: AcReal
    ) -> AcResult:
    pass

def grid_reduce_vec_scal(
    stream: Stream,
    reduction: AcReduction,
    vtxbuf0: VertexBufferHandle,
    vtxbuf1: VertexBufferHandle,
    vtxbuf2: VertexBufferHandle,
    vtxbuf3: VertexBufferHandle,
    result: AcReal
    ) -> AcResult:
    pass

def grid_reduce_xy(
    stream: Stream,
    field: Field,
    profile: Profile,
    reduction: AcReduction
    ) -> AcResult:
    pass

class AccessType(enum.IntEnum):
    access_read = enum.auto()  # (= 0)
    access_write = enum.auto() # (= 1)

def grid_access_mesh_on_disk_synchronous(
    field: VertexBufferHandle,
    dir: str,
    label: str,
    type: AccessType
    ) -> AcResult:
    pass

def grid_disk_access_launch(type: AccessType) -> AcResult:
    pass

def grid_write_slices_to_disk_launch(
    dir: str,
    step_number: int,
    simulation_time: AcReal
    ) -> AcResult:
    """ Asynchronous. Need to call acGridDiskAccessSync afterwards"""
    pass
def grid_write_slices_to_disk_synchronous(
    dir: str,
    step_number: int,
    simulation_time: AcReal
    ) -> AcResult:
    """ Synchronous. No need to call acGridDiskAccessSync afterwards"""
    pass

def grid_write_slices_to_disk_collective_synchronous(
    dir: str,
    step_number: int,
    simulation_time: AcReal
    ) -> AcResult:
    """ Synchronous"""
    pass

def grid_write_mesh_to_disk_launch(dir: str, label: str) -> AcResult:
    """ Asynchronous. Need to call acGridDiskAccessSync afterwards"""
    pass

def grid_disk_access_sync() -> AcResult:
    pass

def grid_read_varfile_to_mesh(
    file: str,
    fields: Field,
    num_fields: int,
    nn: int3,
    rr: int3
    ) -> AcResult:
    pass

def grid_access_mesh_on_disk_synchronous_distributed(
    vtxbuf: VertexBufferHandle,
    dir: str,
    label: str,
    type: AccessType
    ) -> AcResult:
    """ Quick hack for the hero run, will be removed in future builds"""
    pass

def grid_access_mesh_on_disk_synchronous_collective(
    vtxbuf: VertexBufferHandle,
    dir: str,
    label: str,
    type: AccessType
    ) -> AcResult:
    """ Quick hack for the hero run, will be removed in future builds"""
    pass

# Bugged
# AcResult acGridLoadFieldFromFile(const char* path, const VertexBufferHandle field);

# Bugged
# AcResult acGridStoreFieldToFile(const char* path, const VertexBufferHandle field);

class AcTaskType(enum.IntEnum):
    tasktype_no_op = enum.auto()        # (= 0)
    tasktype_compute = enum.auto()      # (= 1)
    tasktype_haloexchange = enum.auto() # (= 2)
    tasktype_boundcond = enum.auto()    # (= 3)
    tasktype_reduce = enum.auto()       # (= 4)
    tasktype_scan = enum.auto()         # (= 5)
    tasktype_ray_update = enum.auto()   # (= 6)
    tasktype_periodic_ray = enum.auto() # (= 7)



def boundary_to_str(boundary: AcBoundary) -> str:
    pass




def analysis_get_bc_info(
    info: AcMeshInfo,
    bc: AcKernel,
    boundary: AcBoundary
    ) -> acAnalysisBCInfo:
    pass




class facet_class_range:
    min: int
    max: int
    def __init__(self, min: int = int(), max: int = int()) -> None:
        """Auto-generated default constructor with named params"""
        pass




@overload
def scan(fields: Field, num_fields: int, direction: int3) -> AcTaskDefinition:
    pass
@overload
def scan(fields: List[Field], ray_direction: int3) -> AcTaskDefinition:
    pass

def periodic_ray(fields: Field, num_fields: int, direction: int3) -> AcTaskDefinition:
    pass









def get_compute_steps_b_cs(graph: AcDSLTaskGraph) -> AcDSLTaskGraph:
    pass



def grid_clear_task_graph_cache() -> AcResult:
    pass





def grid_launch_kernel(
    stream: Stream,
    kernel: AcKernel,
    start: Volume,
    end: Volume
    ) -> AcResult:
    pass





def function_always_false() -> bool:
    pass

# #if __cplusplus
#




def ray_update(
    kernel: AcKernel,
    boundary: AcBoundary,
    ray_direction: int3,
    fields_in: Field,
    num_fields_in: int,
    fields_out: Field,
    num_fields_out: int,
    loader: KernelParamsLoader
    ) -> AcTaskDefinition:
    pass

@overload
def get_optimized_dsl_task_graph(
    graph: AcDSLTaskGraph,
    start: Volume,
    end: Volume
    ) -> Any:
    pass
@overload
def get_optimized_dsl_task_graph(
    graph: AcDSLTaskGraph,
    start: Volume,
    end: Volume,
    globally_imposed_bcs: bool
    ) -> Any:
    pass
@overload
def get_optimized_dsl_task_graph(
    graph: AcDSLTaskGraph,
    globally_imposed_bcs: bool
    ) -> Any:
    pass
@overload
def get_optimized_dsl_task_graph(
    graph: AcDSLTaskGraph,
    globally_imposed_bcs: bool,
    bc_graph: AcDSLTaskGraph
    ) -> Any:
    pass





































# #endif
#

# #endif
####################    </generated_from:astaroth_grid.h>    ####################

# </litgen_stub> // Autogenerated code end
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
