# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub>  // Autogenerated code below! Do not edit!
####################    <generated_from:astaroth_node.h>    ####################

def node_create(id: int, node_config: AcMeshInfo, node: Node) -> AcResult:
    pass

def node_destroy(node: Node) -> AcResult:
    """*
    Resets all devices on the current node.

    @see acNodeCreate()

    """
    pass

def node_print_info(node: Node) -> AcResult:
    """*
    Prints information about the devices available on the current node.

    Requires that Node has been initialized with
    @See acNodeCreate().

    """
    pass


def node_auto_optimize(node: Node) -> AcResult:
    pass

def node_synchronize_stream(node: Node, stream: Stream) -> AcResult:
    pass

#* Deprecated ?
def node_synchronize_vertex_buffer(
    node: Node,
    stream: Stream,
    vtxbuf_handle: VertexBufferHandle
    ) -> AcResult:
    """ Not in Device"""
    pass

def node_synchronize_mesh(node: Node, stream: Stream) -> AcResult:
    """ Not in Device"""
    pass

def node_swap_buffers(node: Node) -> AcResult:
    pass

def node_load_constant(
    node: Node,
    stream: Stream,
    param: AcRealParam,
    value: AcReal
    ) -> AcResult:
    pass

def node_load_vertex_buffer_with_offset(
    node: Node,
    stream: Stream,
    host_mesh: AcMesh,
    vtxbuf_handle: VertexBufferHandle,
    src: int3,
    dst: int3,
    num_vertices: int
    ) -> AcResult:
    """* Deprecated ? Might be useful though if the user wants to load only one vtxbuf. But in this case
     * the user should supply a AcReal* instead of vtxbuf_handle
    """
    pass

def node_load_mesh_with_offset(
    node: Node,
    stream: Stream,
    host_mesh: AcMesh,
    src: int3,
    dst: int3,
    num_vertices: int
    ) -> AcResult:
    pass

def node_load_vertex_buffer(
    node: Node,
    stream: Stream,
    host_mesh: AcMesh,
    vtxbuf_handle: VertexBufferHandle
    ) -> AcResult:
    """* Deprecated ?"""
    pass

def node_load_mesh(node: Node, stream: Stream, host_mesh: AcMesh) -> AcResult:
    pass

def node_set_vertex_buffer(
    node: Node,
    stream: Stream,
    handle: VertexBufferHandle,
    value: AcReal
    ) -> AcResult:
    pass

def node_store_vertex_buffer_with_offset(
    node: Node,
    stream: Stream,
    vtxbuf_handle: VertexBufferHandle,
    src: int3,
    dst: int3,
    num_vertices: int,
    host_mesh: AcMesh
    ) -> AcResult:
    """* Deprecated ?"""
    pass


def node_store_mesh_with_offset(
    node: Node,
    stream: Stream,
    src: int3,
    dst: int3,
    num_vertices: int,
    host_mesh: AcMesh
    ) -> AcResult:
    pass

#* Deprecated ?
def node_store_vertex_buffer(
    node: Node,
    stream: Stream,
    vtxbuf_handle: VertexBufferHandle,
    host_mesh: AcMesh
    ) -> AcResult:
    pass
def node_store_mesh(node: Node, stream: Stream, host_mesh: AcMesh) -> AcResult:
    pass


def node_integrate_substep(
    node: Node,
    stream: Stream,
    step_number: int,
    start: Volume,
    end: Volume,
    dt: AcReal
    ) -> AcResult:
    pass
def node_integrate(node: Node, dt: AcReal) -> AcResult:
    pass
def node_integrate_gbc(node: Node, config: AcMeshInfo, dt: AcReal) -> AcResult:
    pass


def node_periodic_boundcond_step(
    node: Node,
    stream: Stream,
    vtxbuf_handle: VertexBufferHandle
    ) -> AcResult:
    pass
def node_periodic_boundconds(node: Node, stream: Stream) -> AcResult:
    pass


def node_general_boundcond_step(
    node: Node,
    stream: Stream,
    vtxbuf_handle: VertexBufferHandle,
    config: AcMeshInfo
    ) -> AcResult:
    pass
def node_general_boundconds(
    node: Node,
    stream: Stream,
    config: AcMeshInfo
    ) -> AcResult:
    pass


def node_reduce_scal(
    node: Node,
    stream: Stream,
    reduction: AcReduction,
    vtxbuf_handle: VertexBufferHandle,
    result: AcReal
    ) -> AcResult:
    pass
def node_reduce_vec(
    node: Node,
    stream_type: Stream,
    reduction: AcReduction,
    vtxbuf0: VertexBufferHandle,
    vtxbuf1: VertexBufferHandle,
    vtxbuf2: VertexBufferHandle,
    result: AcReal
    ) -> AcResult:
    pass
def node_reduce_vec_scal(
    node: Node,
    stream_type: Stream,
    reduction: AcReduction,
    vtxbuf0: VertexBufferHandle,
    vtxbuf1: VertexBufferHandle,
    vtxbuf2: VertexBufferHandle,
    vtxbuf3: VertexBufferHandle,
    result: AcReal
    ) -> AcResult:
    pass

def node_load_plate(
    node: Node,
    stream: Stream,
    start: int3,
    end: int3,
    host_mesh: AcMesh,
    plate_buffer: AcReal,
    plate: int
    ) -> AcResult:
    pass
def node_store_plate(
    node: Node,
    stream: Stream,
    start: int3,
    end: int3,
    host_mesh: AcMesh,
    plate_buffer: AcReal,
    plate: int
    ) -> AcResult:
    pass
def node_store_ixy_plate(
    node: Node,
    stream: Stream,
    start: int3,
    end: int3,
    host_mesh: AcMesh,
    plate: int
    ) -> AcResult:
    pass
def node_load_plate_xcomp(
    node: Node,
    stream: Stream,
    start: int3,
    end: int3,
    host_mesh: AcMesh,
    plate_buffer: AcReal,
    plate: int
    ) -> AcResult:
    pass
####################    </generated_from:astaroth_node.h>    ####################

# </litgen_stub> // Autogenerated code end
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
