# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub>  // Autogenerated code below! Do not edit!
####################    <generated_from:astaroth_utils.h>    ####################
#
#    Copyright (C) 2014-2021, Johannes Pekkila, Miikka Vaisala.
#
#    This file is part of Astaroth.
#
#    Astaroth is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Astaroth is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
#



class Error:
    model: AcReal
    candidate: AcReal
    abs_error: float
    ulp_error: float
    rel_error: float
    maximum_magnitude: AcReal
    minimum_magnitude: AcReal
    x: int
    y: int
    z: int
    def __init__(
        self,
        model: AcReal = AcReal(),
        candidate: AcReal = AcReal(),
        maximum_magnitude: AcReal = AcReal(),
        minimum_magnitude: AcReal = AcReal(),
        x: int = int(),
        y: int = int(),
        z: int = int()
        ) -> None:
        """Auto-generated default constructor with named params"""
        pass

def host_vertex_buffer_set(
    handle: VertexBufferHandle,
    value: AcReal,
    mesh: AcMesh
    ) -> AcResult:
    pass

def host_mesh_set(value: AcReal, mesh: AcMesh) -> AcResult:
    pass

def host_mesh_apply_periodic_bounds(mesh: AcMesh) -> AcResult:
    pass

def host_mesh_apply_constant_bounds(value: AcReal, mesh: AcMesh) -> AcResult:
    pass

def host_mesh_clear(mesh: AcMesh) -> AcResult:
    pass

def host_integrate_step(mesh: AcMesh, dt: AcReal) -> AcResult:
    """* Applies a full integration step on host mesh using the compact 2N RK3 scheme. The boundaries are
     * not updated after the final substep. A call to acHostMeshApplyPeriodicBounds is required if this
     * is not desired. NOTE: applies boundary conditions on the mesh before the initial substep.
    """
    pass

def host_reduce_scal(
    mesh: AcMesh,
    reduction: AcReduction,
    a: VertexBufferHandle
    ) -> AcReal:
    pass

def host_reduce_vec(
    mesh: AcMesh,
    reduction: AcReduction,
    a: VertexBufferHandle,
    b: VertexBufferHandle,
    c: VertexBufferHandle
    ) -> AcReal:
    pass
def host_reduce_vec_scal(
    mesh: AcMesh,
    reduction: AcReduction,
    a: VertexBufferHandle,
    b: VertexBufferHandle,
    c: VertexBufferHandle,
    d: VertexBufferHandle
    ) -> AcReal:
    pass

def eval_error(label: str, error: Error) -> bool:
    pass
def eval_error_with_maximum_error(
    label: str,
    error: Error,
    max_ulp_error: float
    ) -> bool:
    pass

def verify_mesh(label: str, model: AcMesh, candidate: AcMesh) -> AcResult:
    pass
def verify_mesh_with_maximum_error(
    label: str,
    model: AcMesh,
    candidate: AcMesh,
    max_ulp_error: float
    ) -> AcResult:
    pass
#AcResult (*acVerifyMesh)(const char*, const AcMesh, const AcMesh);

def mesh_diff_write_slice_z(
    path: str,
    model: AcMesh,
    candidate: AcMesh,
    z: int
    ) -> AcResult:
    pass

def mesh_diff_write(path: str, model: AcMesh, candidate: AcMesh) -> AcResult:
    pass
def verify_mesh_comp_domain(label: str, model: AcMesh, candidate: AcMesh) -> AcResult:
    pass

def host_mesh_write_to_file(mesh: AcMesh, id: int) -> AcResult:
    pass

def host_mesh_read_from_file(id: int, mesh: AcMesh) -> AcResult:
    pass

def get_error(model: AcReal, candidate: AcReal) -> Error:
    pass
def host_profile_derz(
    in_: AcReal,
    count: int,
    grid_spacing: AcReal,
    out: AcReal
    ) -> AcResult:
    """ Profiles"""
    pass

def host_profile_derzz(
    in_: AcReal,
    count: int,
    grid_spacing: AcReal,
    out: AcReal
    ) -> AcResult:
    pass

def host_reduce_xy_average(in_: AcReal, dims: AcMeshDims, out: AcReal) -> AcResult:
    pass

def host_write_profile_to_file(
    filepath: str,
    profile: AcReal,
    profile_count: int
    ) -> AcResult:
    """* Writes the host profile to a file"""
    pass

def host_init_profile_to_cosine_wave(
    spacing: AcReal,
    initial_pos: AcReal,
    amplitude: AcReal,
    wavenumber: AcReal,
    mz: int,
    profile: AcReal
    ) -> AcResult:
    """* Inits the profile to cosine wave"""
    pass

def host_init_profile_to_sine_wave(
    spacing: AcReal,
    initial_pos: AcReal,
    amplitude: AcReal,
    wavenumber: AcReal,
    mz: int,
    profile: AcReal
    ) -> AcResult:
    """* Inits the profile to sine wave"""
    pass

def host_init_profile_to_value(
    value: float,
    profile_count: int,
    profile: AcReal
    ) -> AcResult:
    """* Initialize a profile to a constant value"""
    pass


def load_config(config_path: str, config: AcMeshInfo) -> AcResult:
    pass


####################    </generated_from:astaroth_utils.h>    ####################

# </litgen_stub> // Autogenerated code end
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
