#pragma once
#include <stddef.h>
#include <stdint.h>

size_t prod(const size_t count, const size_t* arr);

void cumprod(const size_t count, const size_t* in, size_t* out);

void rshift(const size_t shift, const size_t fill_value, const size_t count, const size_t* in,
            size_t* out);

size_t dot(const size_t count, const size_t* a, const size_t* b);

void factorize(const size_t n_initial, size_t* nfactors, size_t* factors);

/** Requires that array is ordered */
size_t unique(const size_t count, size_t* arr);

void transpose(const size_t* in, const size_t nrows, const size_t ncols, size_t* out);

void contract(const size_t* in, const size_t length, const size_t factor, size_t* out);

int64_t mod(const int64_t a, const int64_t b);

void mod_pointwise(const size_t count, const int64_t* a, const int64_t* b, int64_t* c);

void to_spatial(const size_t index, const size_t ndims, const size_t* shape, size_t* output);

size_t to_linear(const size_t ndims, const size_t* index, const size_t* shape);

void reverse(const size_t count, size_t* arr);

void copy(const size_t count, const size_t* in, size_t* out);

void set(const size_t value, const size_t count, size_t* arr);

void iset(const int value, const size_t count, int* arr);

void add_to_array(const size_t value, const size_t count, size_t* arr);

void add_arrays(const size_t count, const size_t* a, const size_t* b, size_t* c);

// Autogenerated
#define min(a, b)                                                                                  \
    _Generic((a),                                                                                  \
        int: min_int,                                                                              \
        int64_t: min_int64_t,                                                                      \
        size_t: min_size_t,                                                                        \
        float: min_float,                                                                          \
        double: min_double)(a, b)

int min_int(const int a, const int b);
int64_t min_int64_t(const int64_t a, const int64_t b);
size_t min_size_t(const size_t a, const size_t b);
float min_float(const float a, const float b);
double min_double(const double a, const double b);
int min_int(const int a, const int b);
int64_t min_int64_t(const int64_t a, const int64_t b);
size_t min_size_t(const size_t a, const size_t b);
float min_float(const float a, const float b);
double min_double(const double a, const double b);
