#!/bin/bash
#
cmake -B build -S $AC_HOME -DOPTIMIZE_MEM_ACCESSES=ON -DUSE_HIP=OFF -DBUILD_UTILS=ON -DBUILD_SAMPLES=ON -DDOUBLE_PRECISION=OFF -DMULTIGPU_ENABLED=ON -DMPI_ENABLED=OFF && cmake --build build -j
