#!/bin/bash
#
cmake -B build -S  -DCMAKE_BUILD_TYPE=Debug -DMPI_ENABLED=ON -DFFT_ENABLED=OFF -DOPTIMIZE_INPUT_PARAMS=ON -DOPTIMIZE_MEM_ACCESSES=ON -DBUILD_TESTS=ON -DRUNTIME_COMPILATION=ON -DDSL_MODULE_DIR=../DSL && cmake --build build -t line-smoother-multigrid-test -j
