#!/bin/bash
#
cmake -B build -S $AC_HOME -DMPI_ENABLED=ON -DFFT_ENABLED=OFF -DOPTIMIZE_MEM_ACCESSES=ON -DBUILD_TESTS=ON -DRUNTIME_COMPILATION=ON -DDSL_MODULE_DIR=../DSL && cmake --build build -t cg-test -j
