/*
    Copyright (C) 2014-2026, Johannes Pekkila, Miikka Vaisala, Touko Puro.

    This file is part of Astaroth.

    Astaroth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Astaroth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Astaroth.  If not, see <http://www.gnu.org/licenses/>.
*/

/* This header is to be included only by kernels generated by ACC. It provides
 * the common ground shared by all generated kernels. */

#pragma once

#ifndef AC_RUNTIME_SOURCE

#include "host_datatypes.h"

#include "user_defines.h"
#include "stencil_accesses.h"

#include "acc_runtime.h"
#include "acc/implementation.h"
#include "acc/mem_access_helper_funcs.h"
#include "astaroth_cuda_wrappers.h"
#include "device_details.h"
#include "errchk.h"
#include "kernels.h"
#include "math_utils.h"
#include "random.cuh"
#include "static_analysis.h"

typedef void (*Kernel)(const int3, const int3, DeviceVertexBufferArray vba);
__device__ __constant__ AcMeshInfoScalars d_mesh_info;

#define d_multigpu_offset (d_mesh_info.int3_params[AC_multigpu_offset])

#include "dconst_decl.h"
#include "get_address.h"
#include "reduce_helpers_decls.h"
#include "output_value_decl.h"
#include "user_defines_runtime_lib.h"

// TP: We do this ugly macro because I want to keep the generated headers the
// same if we are compiling CPU analysis and the actual GPU code.
// OM: After trying to make it possible to compile kernels across multiple CUs
// the variables need to be referenced using 'extern' and then linked using
// device linking.
#define DECLARE_GMEM_ARRAY(DATATYPE, DEFINE_NAME, ARR_NAME)                    \
  extern __device__ __constant__ DATATYPE*                                     \
      AC_INTERNAL_gmem_##DEFINE_NAME##_arrays_##ARR_NAME
#define DECLARE_CONST_DIMS_GMEM_ARRAY(DATATYPE, DEFINE_NAME, ARR_NAME, LEN)    \
  extern __device__ DATATYPE                                                   \
      AC_INTERNAL_gmem_##DEFINE_NAME##_arrays_##ARR_NAME[LEN]
#define DECLARE_DCONST_ARRAY(DATATYPE, DEFINE_NAME, ARR_NAME, LEN)             \
  extern UNUSED __device__ __constant__ DATATYPE                               \
      AC_INTERNAL_d_##DEFINE_NAME##_arrays_##ARR_NAME[LEN];
#include "dconst_arrays_decl.h"
#include "gmem_arrays_decl.h"
#undef DECLARE_GMEM_ARRAY
#undef DECLARE_CONST_DIMS_GMEM_ARRAY
#undef DECLARE_DCONST_ARRAY

#define PROFILE_X_Y_OR_Z_INDEX(i, j) ((i) + (j) * VAL(AC_mlocal).x)
#define PROFILE_Y_X_OR_Z_INDEX(i, j) ((i) + (j) * VAL(AC_mlocal).y)
#define PROFILE_Z_X_OR_Y_INDEX(i, j) ((i) + (j) * VAL(AC_mlocal).z)
#define DEVICE_VTXBUF_IDX(i, j, k)                                             \
  ((i) + (j) * VAL(AC_mlocal).x + (k) * VAL(AC_mlocal_products).xy)
#define DEVICE_VARIABLE_VTXBUF_IDX(i, j, k, dims)                              \
  ((i) + dims.x * ((j) + (k) * dims.y))
#define LOCAL_COMPDOMAIN_IDX(coord)                                            \
  ((coord.x) + (coord.y) * VAL(AC_nlocal).x +                                  \
   (coord.z) * VAL(AC_nlocal_products).xy)
#define print(...)                                                             \
  {                                                                            \
    if (!DCONST(AC_autotuning_at_work))                                        \
      printf(__VA_ARGS__);                                                     \
  }
#define suppress_unused_warning(X) (void)X
#define longlong long long
#define size(arr)                                                              \
  (int)(sizeof(arr) / sizeof(arr[0])) // Leads to bugs if the user
#define error_message(error, message)
#define fatal_error_message(error, message)
#define ac_dummy_write(field, x, y, z)

#include "device_fields_info.h"
#include "device_output_info.h"

static __device__ UNUSED int3
ac_get_field_halos(const Field& field)
{
  if (vtxbuf_compile_time_device_halos[field] != (int3){-1, -1, -1}) {
    return vtxbuf_compile_time_device_halos[field];
  }
  return VAL(vtxbuf_run_time_device_halos[field]);
}

static __device__ UNUSED bool
ac_field_has_default_dims(const Field& field)
{
  return vtxbuf_device_dims[field] == AC_mlocal;
}

static __device__ UNUSED bool
ac_is_global(const AcRealOutputParam& param)
{
  return real_output_is_global_device[param];
}

static __device__ AcReal
safe_access(const AcReal* arr, const int dims, const int index, const char* name)
{
	if (arr == NULL)
	{
		printf("Trying to access %s which is NULL!\n",name);
		//TP: assert is not defined on Mahti :(
		//assert(false);
		return 0.0;
	}
	else if (index < 0 || index >= dims)
	{
		printf("Trying to access %s out of bounds!: %d\n",name,index);
		//TP: assert is not defined on Mahti :(
		//assert(false);
		return 0.0;
	}
	return arr[index];
}

static __device__ UNUSED AcReal
safe_access(const AcReal* arr, const int dims, const int index, const AcRealArrayParam param)
{
	return safe_access(arr, dims, index,real_array_names__device__[param]);
}

#endif /* AC_RUNTIME_SOURCE */
