#!/bin/bash

cmake -B build -S $AC_HOME -DOPTIMIZE_MEM_ACCESSES=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_ACC_RUNTIME_LIBRARY=ON -DDSL_MODULE_DIR="$AC_HOME/acc-runtime/samples/mhd_modular" -DVERBOSE=ON -DBUILD_UTILS=ON -DBUILD_SAMPLES=ON -DDOUBLE_PRECISION=ON -DMULTIGPU_ENABLED=ON -DMPI_ENABLED=ON && cmake --build build -j
