#pragma once
#include "headers_c.h"

  typedef REAL real3arr[3];
  typedef int int3arr[3];
 typedef bool bool3arr[3];


  integer :: l2i=mx-2*nghost+1;
  integer :: m2i=my-2*nghost+1;
  integer :: n2i=mz-2*nghost+1;
  integer :: l2=mx-nghost;
  integer :: m2=my-nghost;
  integer :: n2=mz-nghost;

  real :: dVol_glob;
  real*:: x,dx_1,dx2,dx_tilde,xprim,dVol_x,dVol1_x;
  real*:: dAxy_x, dAxz_x;
  real*:: y,dy_1,dy2,dy_tilde,yprim,dVol_y,dVol1_y;
  real*:: dAxy_y, dAyz_y;
  real*:: z,dz_1,dz2,dz_tilde,zprim,dVol_z,dVol1_z;
  real*:: dAyz_z, dAxz_z;
  real :: dx,dy,dz,dxmin,dxmax;
  real*:: dx2_bound=0., dy2_bound=0., dz2_bound=0.;
  real*:: xgrid, dx1grid, dxtgrid;
  real*:: ygrid, dy1grid, dytgrid;
  real*::  dz1grid, dztgrid;
  real*:: xglobal;
  real*:: yglobal;
  real*:: zglobal;
  real :: kx_nyq,ky_nyq,kz_nyq;
  real*:: coeffs_1_x;
  real*:: coeffs_1_y;
  real*:: coeffs_1_z;
  logical :: lcartesian_coords=.true.;
  logical :: lspherical_coords=.false.,lcylindrical_coords=.false.;
  logical :: lpipe_coords=.false.;
  logical :: lsphere_in_a_box=.false.,lcylinder_in_a_box=.false.;
  logical :: luse_latitude=.false., luse_oldgrid=.true., luse_xyz1=.false.;
  logical :: lcylindrical_gravity=.false.;
  logical :: luniform_z_mesh_aspect_ratio=.false.;
  logical :: lconcurrent=.true.;
  integer :: tag_foreign=0;
  logical :: lforeign=.false.,lforeign_comm_nblckg=.false.;
  logical :: lyinyang=.false., lyang=.false., lcutoff_corners=.false.;
  integer :: iyinyang_intpol_type=BILIN;
  integer :: nzgrid_eff=nzgrid;
  real:: yy_biquad_weights[4]=impossible;
  integer :: nycut=my, nzcut=mz;
  real :: rel_dang=0.;
  logical :: lcubed_sphere=.false.;
  real :: drcyl,dsurfxy,dsurfyz,dsurfzx;
  real*:: r_mn,r1_mn,r2_mn,r2_weight;
  real*:: sinth,sin1th,sin2th,costh,cotth,sinth_weight;
  real*:: sinph,cosph;
  real*:: cos1th,tanth;
  real*:: sinth_weight_across_proc;
  real*:: rcyl_mn=1.,rcyl_mn1=1.,rcyl_mn2=1.,rcyl_weight;
  real*:: glnCrossSec;
  real*:: rcyl;
  real*:: x12;
  real*:: y12;
  real*:: z12;
  extern real3arr  coeff_grid=1.0;
  extern real3arr  dxi_fact=1.0;
  extern real3arr  trans_width=1.0;
  real*:: xyz_step=1.0,xi_step_frac=1.0,xi_step_width=1.5;
  real :: zeta_grid0=0.0;
  real :: xbot_slice=0.0,xtop_slice=1.0;
  real :: ybot_slice=0.0,ytop_slice=1.0;
  real :: zbot_slice=0.0,ztop_slice=1.0;
  real :: r_rslice=0.;
  integer :: nth_rslice=min(nxgrid,nygrid,nzgrid)/2, nph_rslice=min(nxgrid,nygrid,nzgrid);
  real :: glnCrossSec0=0.0, CrossSec_x1=-1., CrossSec_x2=1., CrossSec_w=.1;
  extern bool3arr  lperi=.true., 
                           lshift_origin=.false., lshift_origin_lower=.false., 
                           lpole=.false., 
                           lequidist=.true.;
  logical :: lignore_nonequi=.false., lcart_equi=.true.;
  integer :: nghost_read_fewer=0;
  real*:: procx_bounds;
  real*:: procy_bounds;
  real*:: procz_bounds;

  extern int3arr  dim_mask=;
  logical :: lall_onesided=.false.;
  extern real3arr  Lxyz=impossible,xyz0=-pi,xyz1=impossible,xyz_star=0.0;
  extern real3arr  Lxyz_loc,xyz0_loc,xyz1_loc;
  real :: r_int=0.,r_ext=impossible;
  real :: r_int_border=impossible,r_ext_border=impossible;
  real :: r_ref=1.,rsmooth=0.,box_volume=1.0;
  real :: Area_xy=1., Area_yz=1., Area_xz=1.;
  real :: mu0=1., mu01=0.;
  logical :: lfirst=.false.,llast=.false.,ldt_paronly=.false.;
  logical :: ldt=.true.;
  real :: dt=0.0;
  real :: tmax=1e33, tstart=0.0;
  real :: max_walltime=0.0;
  real :: dt_incr=0.0, dt0=0.;
  real :: cdt=0.9, cdts=1.0, cdtr=1.0, cdtc=1.0, cdt_poly=1.0;
  real :: cdtv=0.25, cdtv2=0.03, cdtv3=0.01;
  real :: cdtsrc=0.2, cdtf=0.9;
  real :: ddt=0.0, dtinc=0.5, dtdec=0.5;
  real :: dtmin=1.0e-6, dtmax=1.0e37, dt_epsi=1e-7, dt_ratio=1e-5;
  real :: nu_sts=0.1;
  integer :: permute_sts=0;
  integer:: ireset_tstart=2;
  integer :: nt=10000000, it=0, itorder=3, itsub=0, it_timing=0, it_rmv=0;
  integer*:: neighbors = 0;
  integer:: iproc_comm[26] = -1;
  integer :: nproc_comm = 0;
  integer :: ix=-1,iy=-1,iy2=-1,iz=-1,iz2=-1,iz3=-1,iz4=-1;
  integer :: ix_loc=1,iy_loc=1, iy2_loc=1;
  integer :: iz_loc=1,iz2_loc=1, iz3_loc=1, iz4_loc=1;
  integer :: iproc=0,ipx=0,ipy=0,ipz=0,iproc_world=0,ipatch=0;
  logical :: lprocz_slowest=.true., lzorder=.false., lmorton_curve=.false., ltest_bcs=.true.,lsuppress_parallel_reductions=.false.;
  integer :: xlneigh,ylneigh,zlneigh;
  integer :: xuneigh,yuneigh,zuneigh;
  integer :: poleneigh;
  integer :: nprocx_node=0, nprocy_node=0, nprocz_node=0;
  num_after_timestep=5;
  integer*:: updated_var_ranges=0;
  integer :: ighosts_updated=-1;
  real :: x0, y0, z0, Lx, Ly, Lz, wav1=impossible, wav1z=impossible;
  logical :: lini_t_eq_zero=.false.;
  logical :: lini_t_eq_zero_once=.false.;
  real*:: advec_cs2=0.;
  real*:: maxadvec=0., advec2=0., advec2_hypermesh=0.;
  real*:: maxdiffus=0., maxdiffus2=0., maxdiffus3=0., maxsrc=0.;
  real*:: reac_chem, reac_dust;
  real    :: trelax_poly, reac_pchem;
  real*:: alpha_ts=0.0,beta_ts=0.0,dt_beta_ts=1.0,bhat_ts=0.0,dt_bhat_ts=1.0;
  logical :: lfractional_tstep_advance=.false.;
  logical :: lfractional_tstep_negative=.true.;
  logical :: lmaxadvec_sum=.false.,old_cdtv=.false.,leps_fixed=.true.;
  logical :: lmaximal_cdtv=.false., lmaximal_cdt=.false.,lreiterate=.true.;
  logical :: llsode=.false.;
  logical :: lstep1=.true.;
  logical :: lchemonly=.false.;
  logical :: lsplit_second=.false.;
  logical :: lsnap=.false., lsnap_down=.false., lspec=.false., lspec_start=.false., lspec_at_tplusdt=.false.;
  real :: dsnap=100., dsnap_down=0., d1davg=impossible, d2davg=100., dvid=0., dspec=impossible;
  real :: dtracers=0., dfixed_points=0.;
  real :: crash_file_dtmin_factor=-1.0;
  integer :: farray_smooth_width=6;
  integer :: isave=100, ialive=0, isaveglobal=0, nv1_capitalvar=1;
  logical :: lwrite_ts_hdf5=.true., lsave=.false.;
  logical :: lread_aux=.false., lwrite_aux=.false., lwrite_dvar=.false.;
  logical :: lenforce_maux_check=.true., lwrite_avg1d_binary = .false.;
  logical :: lread_oldsnap=.false., lwrite_var_anyway=.false.;
  logical :: lwrite_last_powersnap=.false., lwrite_fsum=.false.;
  logical :: lread_oldsnap_rho2lnrho=.false., lread_oldsnap_nomag=.false.;
  logical :: lread_oldsnap_lnrho2rho=.false., lread_oldsnap_noshear=.false.;
  logical :: lread_oldsnap_nohydro=.false., lread_oldsnap_nohydro_nomu5=.false.;
  logical :: lread_oldsnap_onlyA=.false., lread_oldsnap_mskipvar=.false.;
  logical :: lread_oldsnap_nohydro_efield=.false., lread_oldsnap_nohydro_ekfield=.false.;
  logical :: ldivu_perp=.false.;
  logical :: lread_oldsnap_nopscalar=.false.;
  logical :: lread_oldsnap_notestfield=.false.;
  logical :: lread_oldsnap_notestflow=.false.;
  logical :: lread_oldsnap_notestscalar=.false.;
  logical :: lread_oldsnap_noisothmhd=.false.;
  logical :: lread_oldsnap_nosink=.false.;
  logical :: lnamelist_error=.false., ltolerate_namelist_errors=.false., lparam_nml=.false.;
  logical :: lwrite_dim_again=.true., allproc_print=.true.;
  logical :: lproc_print=.true.;
  logical :: lseparate_persist=.false., ldistribute_persist=.false., lpersist=.true.;
  logical :: lomit_add_data=.false.;
  logical :: save_lastsnap=.true.;
  logical :: noghost_for_isave=.false.;
  logical :: ltec=.false.;
  logical :: lformat=.false.;
  logical :: lread_less=.false., lread_nogrid=.false.;
  logical :: lread_global=.true.;
  logical :: loutput_varn_at_exact_tsnap=.false.;
  logical :: ldirect_access=.false.;
  logical :: lread_from_other_prec=.false.;
  extern int3arr  downsampl=1, firstind=1, ndown=0, ngrid_down;
  logical :: ldownsampl=.false., ldownsampling=.false., lrepair_snap=.false., linterpol_on_repair=.false.;
  logical :: lastaroth_output=.false.;
  integer:: ivar_omit[2]=;
  logical :: lzaver_on_input=.false.;
  logical :: lfatal_num_vector_369=.true.;
  logical :: lsmooth_farray=.false.;
  logical :: lread_scl_factor_file=.false., lread_scl_factor_file_new=.false.;
  real :: scl_factor_target, Hp_target, appa_target, wweos_target;
  integer :: ip=14;
  real :: Omega=0.0, theta=0.0, phi=0.0, qshear=0.0, Sshear=0.0, deltay=0.0;
  logical :: ldensity_nolog=.false., 
             lreference_state=.false., lfullvar_in_slices=.false., 
             lsubstract_reference_state=.false., ldensity_linearstart=.false.;
  logical :: lforcing_cont=.false.;
  logical :: lwrite_slices=.false., lwrite_1daverages=.false., lwrite_2daverages=.false.;
  logical :: lwrite_tracers=.false., lwrite_fixed_points=.false.;
  logical :: lwrite_sound=.false.;
  logical :: lwrite_slice_xy2=.false.,lwrite_slice_xy=.false.,lwrite_slice_xz=.false.,lwrite_slice_yz=.false.;
  logical :: lwrite_slice_xy3=.false.,lwrite_slice_xy4=.false.,lwrite_slice_xz2=.false., lwrite_slice_r=.false.;
  logical :: lgravx=.false.,lgravy=.false.,lgravz=.false.;
  logical :: lgravx_gas=.true.,lgravy_gas=.true.,lgravz_gas=.true.;
  logical :: lgravx_dust=.true.,lgravy_dust=.true.,lgravz_dust=.true.;
  logical :: lgravr=.false.;
  logical :: lwrite_ic=.true.,lnowrite=.false.,lserial_io=.false.;
  logical :: lmodify=.false.;
  logical :: lroot=.true.,lcaproot=.false.,ldebug=.false.,lfft=.true.;
  logical :: lproc_pt=.false., lproc_p2=.false.;
  logical :: lfirst_proc_x=.true.,lfirst_proc_y=.true.,lfirst_proc_z=.true.;
  logical :: lfirst_proc_xy=.true.,lfirst_proc_yz=.true.,lfirst_proc_xz=.true.;
  logical :: lfirst_proc_xyz=.true.;
  logical :: llast_proc_x=.true.,llast_proc_y=.true.,llast_proc_z=.true.;
  logical :: llast_proc_xy=.true.,llast_proc_yz=.true.,llast_proc_xz=.true.;
  logical :: llast_proc_xyz=.true.;
  logical :: lnorth_pole=.false.,lsouth_pole=.false.;
  logical :: lpscalar_nolog=.false.;
  logical :: lalpm=.false., lalpm_alternate=.false.;
  logical :: ldustdensity_log=.false.,lmdvar=.false.,ldcore=.false.;
  logical :: lneutraldensity_nolog=.false.;
  logical :: lvisc_smag=.false.;
  logical :: lslope_limit_diff=.false.;
  logical :: ltemperature_nolog=.false.;
  logical :: ltestperturb=.false.;
  logical :: lweno_transport=.false.;
  logical :: lstart=.false., lrun=.false., lreloading=.false.;
  logical :: ladv_der_as_aux=.false.;
  logical :: lghostfold_usebspline = .false.;
  logical :: lcooling_ss_mz = .false.;
  logical :: lshock_heat = .true.;
  real :: density_scale_factor=impossible;
  logical :: pretend_lnTT=.false.;
