#!/bin/bash
script_dir=$(realpath $(dirname "${BASH_SOURCE[0]}"))
venv=/scratch/project_462000120/olappi/python_data_analysis_env

#TODO: LUMI-specific, please remove and make more resilient

source $venv/bin/activate
OPTS="$@"
printf "$SLURM_JOBID $(date) : Calling plot.py $OPTS\n" >> render.log
TIMEFORMAT=%R
t=$({ time $script_dir/plot.py $@ ; } 2>&1 )
printf "$SLURM_JOBID $(date) : plot.py finished in $t seconds\n" >> render.log
