name: Docs generation with doxygen

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.9.0-devel-ubuntu24.04

    timeout-minutes: 180
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Doxygen and Git
        run: apt-get update && apt-get install -y doxygen graphviz git

      - name: Generate Doxygen documentation
        run: doxygen doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/doxygen/astaroth_doc_html
