name: Build and test all build configurations

on:
  push:
    branches:
      - develop

jobs:
  define-matrices:
    runs-on: ubuntu-latest
    outputs:
      test-builds-matrix: ${{ steps.matrices.outputs.test-builds-matrix }}
      test-matrix: ${{ steps.matrices.outputs.test-matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define matrices
        id: matrices
        run: |
          echo "test-builds-matrix=$(find ./test-builds -mindepth 1 -maxdepth 1 -type d -exec realpath {} ";" | jq -Rsc 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
          echo "test-matrix=$(find ./test -mindepth 1 -maxdepth 1 -type d -exec realpath {} ";" | jq -Rsc 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  compile-base-builds:
    runs-on: ${{ matrix.platform.os }}
    container:
      image: ${{ matrix.platform.container-image }}
    needs: define-matrices
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            container-image: &ubuntu-container nvidia/cuda:13.3.0-devel-ubuntu26.04
          - os: macos-latest
        build-configuration-dir: ${{ fromJSON(needs.define-matrices.outputs.test-builds-matrix) }}
    timeout-minutes: 180

    steps: &build-and-test-steps
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Ubuntu dependencies
        if: ${{ contains(matrix.platform.os, 'ubuntu') }}
        uses: ./.github/actions/install-apt-packages
        with:
          packages: cmake libgsl-dev flex bison openmpi-bin libopenmpi-dev gfortran git python3 python3-numpy python3-pandas

      - name: Install macOS dependencies
        if: ${{ contains(matrix.platform.os, 'macos') }}
        run: |
          brew install cmake gsl open-mpi bison flex python3
          # Makes mac to use the Bison 3.*
          echo "$(brew --prefix bison)/bin" >> "$GITHUB_PATH"
          # Since Python 3.11 installing packages globally is not permitted by default (see PEP 668).
          python3 -m pip config set global.break-system-packages true
          python3 -m pip install pandas numpy

      - name: Force CPU build on macOS
        if: ${{ contains(matrix.platform.os, 'macos') }}
        run: echo AC_CPU_BUILD=ON >> "$GITHUB_ENV"

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CI_CD_KEY }}

      - name: Compile builds and run tests
        uses: ./.github/actions/build-test-astaroth
        with:
          build-configuration-dir: ${{ matrix.build-configuration-dir }}

  compile-and-run-tests:
    runs-on: ${{ matrix.platform.os }}
    container:
      image: ${{ matrix.platform.container-image }}
    needs:
      - define-matrices
      - compile-base-builds
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            container-image: *ubuntu-container
          - os: macos-latest
        build-configuration-dir: ${{ fromJSON(needs.define-matrices.outputs.test-matrix) }}
    timeout-minutes: 180

    steps: *build-and-test-steps
